/* Navegação da análise: os cliques preservam o período da tela de origem. */
let cfoVoltas=[];
const cfoNome=id=>(linhasCaixa.find(x=>x.id===id)||DREModelo.linhas.find(x=>x.id===id))?.nome||id;
const cfoValor=(v,ratio=false)=>v==null?'Não apurado':ratio?v.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%':money(v);
function botaoConta(code,label,periodo=state.periodo){return `<button class="cfo-link" data-cfo-account="${esc(code)}" data-cfo-period="${esc(periodo)}">${esc(label)}</button>`;}
function cfoResumo(reg){
 const a=DRECFO.analise(reg,state.records.find(x=>x.label===state.comparar));
 const frase=a.variacao==null?'Primeiro, complete a leitura do período.':a.variacao<0?'As saídas registradas superaram as entradas.':'As entradas registradas cobriram as saídas.';
 return `<section class="cfo-intro"><div><p class="eyebrow">LEITURA CFO · ${esc(state.periodo)}</p><h2>${frase}</h2><p>${a.variacao==null?'Abra um mês disponível ou confira a atualização da base.':`Diferença de <b>${money(a.variacao)}</b> no caixa considerado. ${a.q.comparavel?'Consulte a composição antes de decidir.':'Este período exige conferência; a leitura não representa um mês fechado.'}`}</p></div>${state.view==='cfo'?'<button class="primary" data-account="2">Abrir composição das saídas →</button>':'<button class="primary" data-go="cfo">Investigar os números →</button>'}</section>`;
}
function renderCFO(reg){
 const a=DRECFO.analise(reg,state.records.find(x=>x.label===state.comparar));
 const cobertura=`<div class="cfo-alert"><b>${esc(a.q.rotulo)}</b><p>${esc(a.q.mensagem)}</p><button data-go="conferencia">Conferir cobertura e origem →</button></div>`;
 const rows=a.ranking.map(x=>`<tr><th>${x.residuo?esc(x.name):botaoConta(x.code,x.name)}<small>${esc(x.code)}</small></th><td class="num">${x.residuo?money(x.value):botaoConta(x.code,money(x.value))}</td><td class="num">${x.peso==null?'—':x.peso.toFixed(1).replace('.',',')+'%'}</td><td>${esc(x.residuo?'Conferir a diferença entre total e detalhamento; não distribuir automaticamente.':x.pergunta)}</td></tr>`).join('');
 const delta=a.variacoes.map(x=>`<div class="cfo-decision"><div><b>${esc(x.name)}</b><p>${esc(state.comparar)}: ${money(x.anterior)} → ${esc(state.periodo)}: ${money(x.atual)}</p><small>Variação ${money(x.delta)}${x.percentual==null?' · sem base percentual':' · '+x.percentual.toFixed(1).replace('.',',')+'%'}; a causa ainda precisa ser conferida.</small></div>${botaoConta(x.code,'Investigar →')}</div>`).join('');
 return cfoResumo(reg)+resumoMovimento(reg)+cobertura+
 card('1. Onde concentrar a investigação',`<p>Grupos de saídas, em ordem de valor absoluto. Cada linha abre sua composição; os grupos não são somados às subcontas.</p>${a.incompleta?'<p class="note">Há valores inválidos na composição. Os pesos estão suspensos; confira o detalhamento.</p>':''}${a.concentracao==null?'':`<p>Os três maiores grupos positivos representam <b>${a.concentracao.toFixed(1).replace('.',',')}%</b> das saídas líquidas registradas${a.concentracao>100?' — há compensações negativas na composição':''}.</p>`}<div class="table-scroll cfo-table"><table><thead><tr><th>Grupo</th><th class="num">Registrado</th><th class="num">Peso nas saídas</th><th>O que conferir na comunicação visual</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Sem composição disponível neste período.</td></tr>'}</tbody></table></div>`)+
 card('2. O que mudou em relação ao outro mês','<p class="hint">Somente contas presentes e com significado compatível nos dois meses recebem diferenças automáticas. Contas novas ou renomeadas continuam no Detalhamento.</p>'+(state.comparar?(a.comparavel?(delta||'<p>Não há diferenças comparáveis nas contas presentes. Contas novas ou renomeadas precisam de revisão no Detalhamento.</p>'):`<p>Comparação com ${esc(state.comparar)} suspensa: períodos, empresas ou critérios ainda não são compatíveis. Os valores originais continuam disponíveis no Detalhamento.</p><button data-go="detalhe">Conferir contas e critérios →</button>`):'<p>Escolha “Comparar com” no topo para investigar diferenças por grupo.</p>'))+
 card('3. Receita necessária para cobrir a operação',`<p>Simulação local, com premissas informadas por você. Separe gastos variáveis de fixos a partir da apuração por competência. Não usamos pagamentos de materiais como consumo automaticamente.</p><form id="cfoCenario"><div class="form-grid"><label>Receita líquida de referência (R$)<input name="receita" type="number" step="0.01" min="0.01" required></label><label>Custos e despesas variáveis dessa receita (R$)<input name="custoVariavel" type="number" step="0.01" min="0" required></label><label>Gastos fixos no mesmo período (R$)<input name="fixos" type="number" step="0.01" min="0" required></label><label>Meta de resultado operacional (R$)<input name="meta" type="number" step="0.01" min="0" value="0" required></label></div><div class="actions"><button class="primary" type="submit">Calcular cenário</button></div></form><div id="cfoCenarioResultado" aria-live="polite"></div><p class="hint">Supõe mix, preços e percentual variável constantes. Não inclui automaticamente juros, tributos sobre o lucro ou capacidade adicional de produção.</p>`,false)+
 card('4. Para conhecer a margem de cada O.S.',`<p>O caixa agregado ainda não fornece lucro por serviço. Para calcular sem distorção, cada O.S. precisa ligar:</p><ol><li>Receita reconhecida, descontos e tributos da venda.</li><li>Materiais efetivamente consumidos: lona, vinil, ACM, acrílico, tintas e perdas.</li><li>Horas de produção e instalação, terceiros e deslocamentos.</li><li>Retrabalho e critérios documentados de rateio da estrutura.</li></ol><p>Estes são requisitos de informação, não custos já apurados nesta tela.</p><button data-go="dre">Abrir DRE e competência →</button>`,false);
}
function abrirAnaliseConta(code,periodo=state.periodo,voltar=false){
 const reg=state.records.find(x=>x.label===periodo)||null;
 if(!voltar)cfoVoltas.push({code,periodo});
 const d=DRECFO.decompor(reg,code),cell=reg?.cells?.find(x=>x.code===code),titulo=cell?.name||cfoNome(code),comp=DREFinancas.composicao(reg,code),other=state.records.find(x=>x.label===state.comparar);
 const cmp=DREFinancas.compararConta(reg,other,code);
 const q=DREFinancas.qualidade(reg);
 const formula=DRECFO.caixa[code]?`<h3>Como o número foi formado</h3><p class="cfo-formula">${esc(d.formula)}</p>${d.partes.map(p=>`<div class="line"><span>${p.sinal<0?'−':'+'} ${botaoConta(p.code,p.name,periodo)}</span><b>${cfoValor(p.value)}</b></div>`).join('')}${d.ausentes?'<p class="hint">A regra histórica considera contas ausentes como zero na decomposição. Elas permanecem identificadas como não informadas; isso não comprova ausência de movimento.</p>':''}`:'';
 const composition=comp.itens.length?`<h3>Composição do valor</h3>${comp.itens.map(c=>`<div class="line"><span>${c.residuo?esc(c.name):botaoConta(c.code,c.name,periodo)}</span><b>${c.residuo?cfoValor(c.value):botaoConta(c.code,cfoValor(c.value),periodo)}</b></div>`).join('')}${comp.incompleta?'<p class="hint">Composição incompleta: há valores inválidos.</p>':''}`:'';
 const hist=state.records.slice().sort((a,b)=>monthSortKey(a.label)-monthSortKey(b.label)).map(r=>{const v=DRECFO.decompor(r,code).value;return `<tr><td>${botaoConta(code,r.label,r.label)}</td><td>${esc(r.cells?.find(x=>x.code===code)?.name||titulo)}</td><td class="num">${botaoConta(code,cfoValor(v),r.label)}</td><td>${esc(F.qualidade(r).rotulo)}</td></tr>`;}).join('');
 const origin=DRECFO.origem(reg,code);
 dialog(titulo,`<div class="cfo-detail-head"><span>${esc(periodo)} · ${esc(q.rotulo)}</span><strong>${cfoValor(d.value)}</strong><p>${esc(reg?.company||'Escopo não informado')} · ${reg?.origem==='erp'?'Mubisys':'Histórico / planilha'} · registro ${esc(dataBR(q.coletadoEm))}</p></div><div class="actions">${cfoVoltas.length>1?'<button id="cfoVoltar">← Voltar à análise anterior</button>':''}<button id="cfoDetailPDF">Baixar esta análise em PDF</button></div><p class="note">${esc(DRECFO.pergunta(titulo))}</p>${cmp.permitida?`<p>Diferença para ${esc(other.label)}: <b>${money(cmp.delta)}</b>${cmp.percentual==null?'':' ('+cmp.percentual.toFixed(1).replace('.',',')+'%)'}. Variação não identifica a causa sozinha.</p>`:''}${formula}${composition}<h3>Histórico da conta</h3><div class="table-scroll"><table><thead><tr><th>Mês</th><th>Nome no mês</th><th class="num">Valor</th><th>Cobertura</th></tr></thead><tbody>${hist}</tbody></table></div><p class="hint">Contas renomeadas ou com outra classificação não são comparadas automaticamente.</p><h3>Até onde os dados permitem ir</h3><p>${esc(origin.nota)}</p>${origin.disponivel?`<p>${origin.eventos.length} movimentos de origem disponíveis.</p><button id="cfoVerOrigem">Abrir movimentos desta coleta</button>`:''}`);
 wireCFO($$('detailContent'));
 if($$('cfoVoltar'))$$('cfoVoltar').onclick=()=>{cfoVoltas.pop();const p=cfoVoltas.at(-1);abrirAnaliseConta(p.code,p.periodo,true);};
 $$('cfoDetailPDF').onclick=()=>exportarCFO({tipo:'conta',code,periodo},$$('cfoDetailPDF'));
 if($$('cfoVerOrigem'))$$('cfoVerOrigem').onclick=()=>abrirOrigemCFO(reg,code,0);
}
function abrirOrigemCFO(reg,code,page){
 const eventos=DRECFO.origem(reg,code).eventos,parts=eventos.slice(page*80,(page+1)*80);
 dialog('Movimentos de origem · '+reg.label,`<p>${eventos.length} movimentos · página ${page+1} de ${Math.max(1,Math.ceil(eventos.length/80))}. Origem da coleta, sem reclassificação.</p><div class="table-scroll"><table><thead><tr><th>Data</th><th>Empresa / título</th><th>Conta original / O.S.</th><th class="num">Valor</th></tr></thead><tbody>${parts.map(e=>`<tr><td>${esc(e.data)}</td><td>${esc(e.empresa)}<br>${esc(e.tituloId)}</td><td>${esc(e.contaOrigem)} ${esc(e.nomeConta)}<br>${esc((e.ordensServico||[]).join(', '))}</td><td class="num">${cfoValor(e.valor)}</td></tr>`).join('')}</tbody></table></div><div class="actions"><button id="origVoltar">← Voltar à conta</button><button id="origAnterior" ${page?'':'disabled'}>Anterior</button><button id="origProximo" ${(page+1)*80<eventos.length?'':'disabled'}>Próxima</button><button id="origPDF">PDF com todos os movimentos</button></div>`);
 $$('origVoltar').onclick=()=>abrirAnaliseConta(code,reg.label,true);$$('origAnterior').onclick=()=>abrirOrigemCFO(reg,code,page-1);$$('origProximo').onclick=()=>abrirOrigemCFO(reg,code,page+1);$$('origPDF').onclick=()=>exportarCFO({tipo:'origem',code,periodo:reg.label},$$('origPDF'));
}
function abrirRubricaCFO(id,label,base){
 if(base==='caixa'){cfoVoltas=[];abrirAnaliseConta(id,label);return;}
 const reg=DRECompetencia.obter(state.cfg,safeId(label)),calc=DREModelo.calcular(reg?.valores||{}),row=DREModelo.linhas.find(x=>x.id===id),parts=DRECFO.competencia[id]||[[id,1]],ratio=DRECFO.margens[id];
 const field=DREModelo.campos.find(x=>x.id===id);
 const link=k=>`<button class="cfo-link" data-cfo-rubrica="${esc(k)}" data-cfo-period="${esc(label)}" data-cfo-base="competencia">${esc(cfoNome(k))}</button>`;
 dialog((row?.nome||id)+' · '+label,`<div class="cfo-detail-head"><span>Por competência · ${esc(statusCompetencia(reg))}</span><strong>${cfoValor(calc[id],!!ratio)}</strong><p>Empresas: ${esc(reg?.company||'Não informadas')} · Fonte: ${esc(reg?.fonte||'Não informada')} · Revisão: ${esc(dataBR(reg?.revisadoEm))}</p></div><h3>Como interpretar</h3><p>${esc(field?.ajuda||'Subtotal calculado pelas rubricas abaixo. Campos ausentes impedem a apuração, em vez de serem tratados como zero.')}</p>${ratio?`<p>${link(ratio)} ÷ ${link('liquida')} × 100. Exige receita líquida positiva.</p>`:parts.map(([k,s])=>`<div class="line"><span>${s<0?'−':'+'} ${k===id?esc(cfoNome(k)):link(k)}</span><b>${cfoValor(calc[k])}</b></div>`).join('')}<p class="hint">Esta apuração guarda valores mensais e fonte informada. Não há documentos ou lançamentos individuais vinculados às rubricas; o painel não inventa essa trilha.</p><div class="actions"><button id="rubricaPDF">PDF desta rubrica</button><button id="rubricaDRE">Voltar ao DRE mensal</button></div>`);
 wireCFO($$('detailContent'));$$('rubricaPDF').onclick=()=>exportarCFO({tipo:'rubrica',id,periodo:label,base},$$('rubricaPDF'));$$('rubricaDRE').onclick=()=>$$('detailDialog').close();
}
function wireCFO(root=document){
 root.querySelectorAll('[data-cfo-account]').forEach(b=>b.onclick=()=>{if(root===document)cfoVoltas=[];abrirAnaliseConta(b.dataset.cfoAccount,b.dataset.cfoPeriod||state.periodo);});
 root.querySelectorAll('[data-cfo-acumulado]').forEach(b=>b.onclick=()=>abrirAcumuladoCFO(b.dataset.cfoAcumulado));
 root.querySelectorAll('[data-cfo-rubrica]').forEach(b=>b.onclick=()=>abrirRubricaCFO(b.dataset.cfoRubrica,b.dataset.cfoPeriod,b.dataset.cfoBase));
 if(root!==document)return;
 if($$('cfoPDF'))$$('cfoPDF').onclick=()=>exportarCFO({tipo:state.view==='dre'?'anual':state.view==='custos'?'custos':state.view==='detalhe'?'contas':'executivo',periodo:state.periodo,base:state.view==='dre'?dreUI.base:'caixa'},$$('cfoPDF'));
 if($$('cfoCenario'))$$('cfoCenario').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)])),s=DRECFO.sensibilidade(p);$$('cfoCenarioResultado').innerHTML=s.valido?`<div class="note"><b>Cenário informado · não é projeção automática</b>${linha('Margem de contribuição',cfoValor(s.mc*100,true))}${linha('Receita para cobrir os gastos fixos',s.equilibrio)}${linha('Receita para a meta operacional',s.vendaMeta,true)}<p>Fórmula: (gastos fixos + meta) ÷ margem de contribuição.</p><button id="cenarioPDF">Baixar cenário em PDF</button></div>`:`<p class="note">${esc(s.motivo)}</p>`;if(s.valido)$$('cenarioPDF').onclick=()=>exportarCFO({tipo:'cenario',periodo:state.periodo,premissas:p,cenario:s},$$('cenarioPDF'));};
}

function metricRubricaCFO(id,label,value,desc){return `<button class="metric" data-cfo-rubrica="${esc(id)}" data-cfo-period="${esc(state.periodo)}" data-cfo-base="competencia"><span class="label">${esc(label)}</span><strong>${cfoValor(value,!!DRECFO.margens[id])}</strong><small>${esc(desc)} · Clique para entender</small></button>`;}
function abrirAcumuladoCFO(id){
 const d=dadosDRE(),ratio=!!DRECFO.margens[id];
 dialog(cfoNome(id)+' · acumulado',`<div class="cfo-detail-head"><span>Janeiro até ${esc(state.periodo)} · ${d.competencia?'Competência':'Caixa gerencial'}</span><strong>${cfoValor(d.soma[id],ratio)}</strong></div><p>${ratio?'A margem acumulada é a razão dos totais; não é a média dos percentuais mensais.':'Soma dos valores mensais abaixo, sem completar meses ausentes.'} ${d.mesmoEscopo?'':'Há escopos diferentes; a soma está bloqueada.'}</p>${d.cols.slice(0,d.ate).map((x,i)=>`<div class="line"><span>${esc(x.label)} · ${esc(d.competencia?statusCompetencia(x.comp):F.qualidade(x.reg).rotulo)}</span><button class="cfo-value" data-cfo-rubrica="${esc(id)}" data-cfo-period="${esc(x.label)}" data-cfo-base="${d.competencia?'competencia':'caixa'}">${cfoValor(d.valores[i][id],ratio)}</button></div>`).join('')}<p class="hint">Meses parciais não viram meses fechados na soma. Ausência impede o acumulado.</p><button id="acumuladoPDF">Baixar demonstrativo completo em PDF</button>`);
 wireCFO($$('detailContent'));$$('acumuladoPDF').onclick=()=>exportarCFO({tipo:'anual',periodo:state.periodo,base:dreUI.base},$$('acumuladoPDF'));
}
