/* Visões mensais, separadas por regime. Nenhuma gravação acontece ao navegar. */
const dreUI={base:'caixa',detalhar:false};
const linhasCaixa=[
 ['entradas','(+) Recebimentos considerados','total','Recebimento'],
 ['operacionais','Recebimentos operacionais','detail','Caixa operacional'],
 ['emprestimos','Entradas de empréstimos','detail','Principal de empréstimo'],
 ['rendimentos','Rendimentos financeiros recebidos','detail','Receita financeira'],
 ['naoIdentificadas','Entradas a identificar','detail','Conciliação'],
 ['outrasEntradas','Outras entradas','detail','Recebimento'],
 ['saidas','(−) Pagamentos considerados','total','Pagamento'],
 ['pagamentosOperacionais','Pagamentos classificados na operação','detail','Caixa operacional'],
 ['socios','Sócios e arrendamento','detail','Pró-labore'],
 ['parcelasAtivos','Parcelas de ativos','detail','CAPEX'],
 ['investimentos','Investimentos classificados','detail','Investimento'],
 ['dividas','Dívidas classificadas','detail','Principal de empréstimo'],
 ['transferencias','Transferências entre empresas','detail','Transferência'],
 ['pendentes','Saídas sem detalhamento','detail','Conciliação'],
 ['variacao','(=) Variação do caixa considerado','result','Variação de caixa']
].map(([id,nome,tipo,termo])=>({id,nome,tipo,termo}));
function mesesDRE(){const ano=Number(state.periodo.split('/')[1])||new Date().getFullYear();return PT_MON.map((m,i)=>{const label=m+'/'+ano,reg=state.records.find(r=>monthSortKey(r.label)===ano*12+i)||null,comp=DRECompetencia.obter(state.cfg,safeId(label));return {label,reg,comp};});}
function valorDRE(v,ratio=false){return v==null?'<span class="muted" title="Não apurado: faltam informações">—</span>':ratio?v.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%':money(v);}
function dadosDRE(){
 const competencia=dreUI.base==='competencia',cols=mesesDRE(),ate=cols.findIndex(x=>x.label===state.periodo)+1||12,periodos=cols.slice(0,ate);
 const valores=cols.map(x=>competencia?DREModelo.calcular(x.comp?.valores||{}):x.reg&&F.valorConta(x.reg,'1')!=null&&F.valorConta(x.reg,'2')!=null?F.resumo(x.reg):{});
 const escopos=new Set(periodos.filter(x=>competencia?x.comp:x.reg).map(x=>competencia?x.comp.company.trim().toLocaleLowerCase('pt-BR'):JSON.stringify([x.reg.company,x.reg.basis,x.reg.qualidade?.escopo,x.reg.qualidade?.regra])));
 let soma={};if(escopos.size<=1){if(competencia)soma=DREModelo.acumulado(periodos.map(x=>x.comp));else for(const row of linhasCaixa){const vs=valores.slice(0,ate).map(v=>v[row.id]);soma[row.id]=vs.some(v=>v==null)?null:vs.reduce((s,v)=>s+Math.round(v*100),0)/100;}}
 return {competencia,cols,ate,valores,soma,mesmoEscopo:escopos.size<=1,linhas:(competencia?DREModelo.linhas:linhasCaixa).filter(r=>dreUI.detalhar||r.tipo!=='detail')};
}
function statusCompetencia(c){return !c?'Não preenchido':c.estado==='preenchido'?'Preenchido · a validar':'Preenchimento parcial';}
function tabelaDRE(d){return `<div class="dre-table-wrap" tabindex="0" role="region" aria-label="Demonstrativo mensal. Role para acompanhar os meses."><table class="dre-table"><caption>${d.competencia?'DRE por competência':'Demonstrativo gerencial de caixa'} · ${esc(state.periodo.split('/')[1])} · valores em R$ · — = não apurado</caption><thead><tr><th scope="col">Conta / resultado</th>${d.cols.map(x=>`<th scope="col" class="num ${x.label===state.periodo?'selected-month':''}"><button data-period="${esc(x.label)}">${esc(x.label)}</button><small>${esc(d.competencia?statusCompetencia(x.comp):F.qualidade(x.reg).rotulo)}</small></th>`).join('')}<th scope="col" class="num">Acumulado<small>Jan até ${esc(state.periodo.split('/')[0])}</small></th></tr></thead><tbody>${d.linhas.map(r=>`<tr class="dre-row-${r.tipo}"><th scope="row"><span>${esc(r.nome)}</span><button class="term-help" data-term="${esc(r.termo)}" aria-label="Entender ${esc(r.termo)}">?</button></th>${d.valores.map((v,i)=>`<td class="num ${d.cols[i].label===state.periodo?'selected-month':''} ${v[r.id]<0?'neg':''}"><button class="cfo-value" data-cfo-rubrica="${esc(r.id)}" data-cfo-period="${esc(d.cols[i].label)}" data-cfo-base="${d.competencia?'competencia':'caixa'}" aria-label="Analisar ${esc(r.nome)} em ${esc(d.cols[i].label)}">${valorDRE(v[r.id],r.tipo==='ratio')}</button></td>`).join('')}<td class="num dre-accumulated"><button class="cfo-value" data-cfo-acumulado="${esc(r.id)}" aria-label="Analisar acumulado de ${esc(r.nome)}">${valorDRE(d.soma[r.id],r.tipo==='ratio')}</button></td></tr>`).join('')}</tbody></table></div>`;}
function renderDRE(){
 const d=dadosDRE(),atual=d.cols.find(x=>x.label===state.periodo),calc=atual?d.valores[d.cols.indexOf(atual)]:{};
 const controls=`<div class="dre-controls"><div class="dre-switch" role="group" aria-label="Regime do demonstrativo"><button data-dre-base="caixa" aria-pressed="${!d.competencia}">🏦 Gerencial de caixa</button><button data-dre-base="competencia" aria-pressed="${d.competencia}">📑 Por competência</button></div><div class="actions"><button id="dreCSV">↓ Planilha CSV</button><button id="drePrint">Imprimir / PDF</button></div></div>`;
 const intro=d.competencia?`<div class="dre-intro"><div><h2>O resultado econômico, mês a mês</h2><p>Receita, custos, despesas e lucro no período em que aconteceram.</p><small>${esc(atual?.comp?atual.comp.company+' · Fonte: '+atual.comp.fonte+' · Revisão: '+dataBR(atual.comp.revisadoEm):'A base atual contém caixa. A competência precisa de valores reconhecidos e revisados para cada mês.')}</small></div><button id="editarCompetencia" class="primary" ${state.permissoes.admin?'':'disabled'}>${atual?.comp?'Revisar':'Preencher'} ${esc(state.periodo)}</button></div>${!state.permissoes.admin?'<p class="hint">O preenchimento compartilhado está disponível para administradores do DRE.</p>':''}`:`<div class="dre-intro"><div><h2>O movimento do dinheiro, mês a mês</h2><p>Recebimentos, pagamentos e a diferença entre os dois.</p><small>Base gerencial filtrada por “compõe DRE”. Não representa lucro por competência nem saldo bancário disponível.</small></div></div>`;
 const cards=d.competencia?`<div class="cards finance-kpis">${metricRubricaCFO('liquida','Receita líquida',calc.liquida,state.periodo)}${metricRubricaCFO('liquido','Lucro / prejuízo líquido',calc.liquido,'Após financeiro e tributos')}${metricRubricaCFO('margemLiquida','Margem líquida',calc.margemLiquida,'Lucro líquido ÷ receita líquida')}</div>`:resumoMovimento(atual?.reg);
 const dadosNota=d.competencia?'Campos não preenchidos impedem os subtotais que dependem deles. Zero deve ser confirmado como zero ou não aplicável. EBITDA usa as operações continuadas e soma de volta a depreciação e amortização já incluídas nos custos e despesas.':'Os totais conservam a classificação de cada mês. Abra as rubricas para ver a decomposição. Meses parciais e mudanças de classificação exigem conferência antes de comparar.';
 const chart=d.competencia&&!d.valores.some(v=>v.liquida!=null||v.liquido!=null)?painelGrafico('Receita líquida e resultado ao longo do ano','Gráfico por competência','<p class="empty">O gráfico será preenchido conforme as receitas e os resultados mensais forem apurados.</p>'):d.competencia?painelGrafico('Receita líquida e resultado ao longo do ano','Valores por competência informados; mês vazio permanece sem barra.',graficoBarras(d.cols.map((x,i)=>({label:x.label,reg:x.comp,qualidade:{comparavel:false,rotulo:statusCompetencia(x.comp)},receita:d.valores[i].liquida,resultado:d.valores[i].liquido})),[{chave:'receita',nome:'Receita líquida',cor:'var(--chart-in)'},{chave:'resultado',nome:'Lucro / prejuízo',cor:'var(--chart-cost)'}],'Receita e resultado por competência')):graficoEvolucao();
 return controls+`<div class="dre-period-control"><label>Mês de referência<input id="drePeriodo" type="month" min="2000-01" max="2100-12" value="${state.periodo.split('/')[1]}-${String(PT_MON.indexOf(state.periodo.split('/')[0])+1).padStart(2,'0')}"></label></div>`+intro+cards+painelGrafico(d.competencia?'Demonstração do resultado':'Demonstrativo de caixa',`Janeiro a dezembro · acumulado até ${state.periodo}`,`<div class="actions"><label class="check-label"><input id="dreDetalhar" type="checkbox" ${dreUI.detalhar?'checked':''}>Abrir rubricas detalhadas</label><button id="dreMesAtual">Ir à coluna de ${esc(state.periodo)}</button></div>${tabelaDRE(d)}<p class="hint">${dadosNota}</p><p class="hint">O acumulado fica sem valor quando falta algum mês ou os escopos diferem. Meses parciais continuam parciais no acumulado. ${d.mesmoEscopo?'':'Há empresas ou critérios diferentes neste ano.'}</p>`)+chart+(atual?.comp?.notas?card('Notas de '+state.periodo,`<p class="preserve-lines">${esc(atual.comp.notas)}</p>`,false):'');
}
function wireDRE(){
 if($$('drePeriodo'))$$('drePeriodo').onchange=e=>{if(!e.target.validity.valid||!e.target.value)return;const [y,m]=e.target.value.split('-');state.periodo=PT_MON[Number(m)-1]+'/'+y;render();};
 document.querySelectorAll('[data-dre-base]').forEach(b=>b.onclick=()=>{dreUI.base=b.dataset.dreBase;render();});
 if($$('dreDetalhar'))$$('dreDetalhar').onchange=e=>{dreUI.detalhar=e.target.checked;render();};
 if($$('editarCompetencia'))$$('editarCompetencia').onclick=()=>abrirCompetencia(state.periodo);
 if($$('dreMesAtual'))$$('dreMesAtual').onclick=()=>{const wrap=document.querySelector('.dre-table-wrap'),cell=wrap?.querySelector('thead .selected-month');if(wrap&&cell)wrap.scrollTo({left:Math.max(0,cell.offsetLeft-wrap.querySelector('th').offsetWidth),behavior:'smooth'});};
 if($$('drePrint'))$$('drePrint').onclick=()=>exportarCFO({tipo:'anual',periodo:state.periodo,base:dreUI.base},$$('drePrint'));
 if($$('dreCSV'))$$('dreCSV').onclick=()=>{const d=dadosDRE(),rows=[[(d.competencia?'DRE por competência':'Caixa gerencial'),...d.cols.map(x=>x.label),'Acumulado até '+state.periodo],['Situação',...d.cols.map(x=>d.competencia?statusCompetencia(x.comp):F.qualidade(x.reg).rotulo),'Depende de todos os meses e do mesmo escopo'],['Empresa / escopo',...d.cols.map(x=>(d.competencia?x.comp:x.reg)?.company||'Não informado'),''],...d.linhas.map(r=>[r.nome,...[...d.valores,d.soma].map(v=>v[r.id]==null?'Não apurado':v[r.id].toFixed(r.tipo==='ratio'?4:2).replace('.',',')+(r.tipo==='ratio'?'%':''))])];download('dre-'+dreUI.base+'-'+state.periodo.split('/')[1]+'.csv','\ufeff'+rows.map(r=>r.map(x=>'"'+String(x).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\n'),'text/csv');};
}
function abrirCompetencia(label){
 if(!state.permissoes.admin)return;
 const session=STORE_KEY;const id=safeId(label),original=structuredClone(DRECompetencia.obter(state.cfg,id));
 let draft=original||{label,company:'',fonte:'',notas:'',valores:{}};
 const grupos=[...new Set(DREModelo.campos.map(c=>c.grupo))];
 const mostrar=()=>{
 dialog('Competência · '+label,`<form id="competenciaForm"><p>Informe valores reconhecidos neste mês. Receber uma venda antiga ou pagar uma compra não define a competência. Use a apuração, o balancete ou registros conferidos.</p><div class="form-grid"><label>Empresas incluídas<input name="company" value="${esc(draft.company)}" placeholder="Ex.: Impresilk + Universo" required maxlength="200"></label><label>Fonte da apuração<input name="fonte" value="${esc(draft.fonte)}" placeholder="Ex.: balancete revisado de setembro" required maxlength="300"></label></div>${grupos.map(g=>`<fieldset class="competencia-group"><legend>${esc(g)}</legend><div class="form-grid">${DREModelo.campos.filter(c=>c.grupo===g).map(c=>`<label>${esc(c.nome)} (R$)<input name="${c.id}" type="text" inputmode="decimal" value="${draft.valores[c.id]==null?'':Number(draft.valores[c.id]).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}" placeholder="Não informado" maxlength="24"><small>${esc(c.ajuda)}</small></label>`).join('')}</div></fieldset>`).join('')}<button type="button" id="competenciaZeros">Marcar campos vazios como zero / não aplicável</button><label>Notas e critérios<textarea name="notas" rows="3" maxlength="3000">${esc(draft.notas)}</textarea></label><p id="competenciaErro" class="neg" role="alert"></p><div class="actions"><button class="primary" type="submit">Revisar valores antes de salvar</button><button id="competenciaCancelar" type="button">Cancelar</button></div></form>`);
 $$('competenciaCancelar').onclick=()=>$$('detailDialog').close();
 $$('competenciaZeros').onclick=()=>{DREModelo.campos.forEach(c=>{const el=$$('competenciaForm').elements.namedItem(c.id);if(!el.value.trim())el.value='0,00';});toast('Campos vazios marcados como zero. Confira antes de salvar.');};
 $$('competenciaForm').onsubmit=e=>{e.preventDefault();try{const fd=new FormData(e.target),valores={};for(const c of DREModelo.campos){const raw=String(fd.get(c.id)).trim();valores[c.id]=raw===''?null:parseNum(raw);}draft={...draft,label,company:String(fd.get('company')).trim(),fonte:String(fd.get('fonte')).trim(),notas:String(fd.get('notas')),valores:DREModelo.validar(valores)};if(!draft.company||!draft.fonte)throw new Error('Informe empresas e fonte da apuração.');if(Object.values(draft.valores).every(v=>v==null))throw new Error('Preencha ao menos uma rubrica.');revisar();}catch(err){$$('competenciaErro').textContent=err.message;}};
 };
 const revisar=()=>{
  const calc=DREModelo.calcular(draft.valores),pendentes=DREModelo.campos.filter(c=>draft.valores[c.id]==null);
  dialog('Conferir competência · '+label,`<p><b>${esc(draft.company)}</b><br>Fonte: ${esc(draft.fonte)}</p><p class="note">${pendentes.length?`${pendentes.length} rubricas sem valor. O mês será salvo como parcial.`:'Todas as rubricas foram preenchidas. Isso não substitui a validação contábil.'}</p><div class="table-scroll"><table><thead><tr><th>Rubrica</th><th class="num">Na nuvem</th><th class="num">Nova versão</th></tr></thead><tbody>${DREModelo.campos.map(c=>`<tr><th>${esc(c.nome)}</th><td class="num">${valorDRE(original?.valores?.[c.id])}</td><td class="num">${valorDRE(draft.valores[c.id])}</td></tr>`).join('')}</tbody></table></div>${linha('Receita líquida',calc.liquida??'Não apurado')}${linha('Lucro / prejuízo líquido',calc.liquido??'Não apurado',true)}<label class="check-label"><input id="competenciaConfirmar" type="checkbox">Conferi o mês, as empresas, a fonte e os valores desta apuração.</label><p id="competenciaSaveErro" class="neg" role="alert"></p><div class="actions"><button id="competenciaSalvar" class="primary" disabled>Salvar competência na nuvem</button><button id="competenciaVoltar">Voltar e ajustar</button><button id="competenciaCopia">Baixar cópia desta edição</button></div>`);
  const registro={...draft,revisao:crypto.randomUUID(),revisadoEm:new Date().toISOString()};
  $$('competenciaConfirmar').onchange=e=>$$('competenciaSalvar').disabled=!e.target.checked;
  $$('competenciaVoltar').onclick=mostrar;
  $$('competenciaCopia').onclick=()=>download('competencia-'+id+'.json',JSON.stringify(registro,null,2));
  $$('competenciaSalvar').onclick=async()=>{if(!$$('competenciaConfirmar').checked)return;const btn=$$('competenciaSalvar');btn.disabled=true;$$('competenciaVoltar').disabled=true;$$('competenciaConfirmar').disabled=true;try{const res=await DRECompetencia.salvar({api,admin:state.permissoes.admin,id,original,registro});if(session!==STORE_KEY||!state.D)return;state.cfg=res.cfg;state.cfgVersion=res.atualizadoEm;$$('detailDialog').close();render();toast('Competência de '+label+' salva e confirmada na nuvem.');}catch(err){if($$('competenciaSaveErro'))$$('competenciaSaveErro').textContent=err.message;else toast(err.message,'err');btn.disabled=false;if($$('competenciaVoltar'))$$('competenciaVoltar').disabled=false;if($$('competenciaConfirmar'))$$('competenciaConfirmar').disabled=false;}};
 };
 mostrar();
}
