/* Explicações originais e exemplos ilustrativos; não contêm dados de clientes. */
var GlossarioFinanceiro=(()=>{
 const grupos={dre:'DRE e resultado',caixa:'Caixa e capital de giro',custos:'Custos e operação',credito:'Crédito e matemática',contabil:'Contabilidade e conferência'};
 const termos=[
 ['DRE','dre','Demonstração do Resultado do Exercício. Organiza receitas, deduções, custos e despesas para explicar o lucro ou prejuízo de um período.','Uma venda entregue em setembro pode entrar no resultado de setembro mesmo quando o cliente paga em outubro.','Receitas − custos − despesas ± outros resultados = resultado líquido'],
 ['Competência','dre','Reconhecimento no período em que o fato econômico ocorre, conforme os critérios aplicáveis, independentemente de quando o dinheiro é recebido ou pago.','Energia consumida em agosto e paga em setembro pertence à despesa de agosto.'],
 ['Regime de caixa','caixa','Acompanha recebimentos e pagamentos pela data do movimento financeiro.','Uma venda de agosto recebida em setembro aumenta os recebimentos de setembro.'],
 ['Receita','dre','Valor reconhecido pela venda de bens ou prestação de serviços. A emissão, a entrega e o recebimento podem acontecer em momentos diferentes.','Receber um empréstimo aumenta o caixa, mas não é receita de venda.'],
 ['Faturamento','dre','Termo usado para o valor das vendas faturadas. A data da nota, sozinha, pode não determinar o reconhecimento contábil da receita.','Uma nota antecipada exige conferir a entrega antes de reconhecer toda a receita.'],
 ['Receita bruta','dre','Vendas reconhecidas antes das deduções da receita.','Produtos de R$ 8 mil mais serviços de R$ 2 mil formam R$ 10 mil de receita bruta.'],
 ['Deduções','dre','Reduções da receita bruta, como devoluções, cancelamentos, descontos incondicionais e tributos incidentes nas vendas, conforme a apuração.','R$ 10 mil de receita menos R$ 1 mil de deduções deixam R$ 9 mil líquidos.'],
 ['Devoluções','dre','Reduções das vendas decorrentes de mercadorias devolvidas ou cancelamentos reconhecidos.','Um pedido devolvido pode reduzir a receita e exigir ajuste do custo ou do estoque.'],
 ['Desconto','dre','Redução do preço. O desconto incondicional integra as deduções; descontos financeiros dependem de condição e exigem classificação pela natureza.','Um desconto concedido no preço da venda difere de um abatimento por pagamento antecipado.'],
 ['Tributos sobre vendas','dre','Tributos associados à receita conforme atividade, regime tributário e apuração.','Use os tributos efetivamente apurados, sem aplicar uma alíquota genérica a todas as vendas.'],
 ['Receita líquida','dre','Receita bruta após as deduções. É a base de receita usada nas margens deste painel.','R$ 100 mil de receita bruta menos R$ 12 mil de deduções = R$ 88 mil líquidos.','Receita bruta − deduções'],
 ['CPV / CMV / CSP','custos','Custo dos Produtos Vendidos, das Mercadorias Vendidas ou dos Serviços Prestados. Relaciona os recursos consumidos àquilo que gerou receita no período.','Comprar material em setembro para um serviço futuro não transforma toda a compra em custo de setembro.'],
 ['Lucro bruto','dre','Resultado após descontar da receita líquida o custo dos produtos ou serviços vendidos. Ainda faltam despesas e demais resultados.','Receita líquida de R$ 90 mil e custos de R$ 50 mil deixam lucro bruto de R$ 40 mil.','Receita líquida − CPV / CMV / CSP'],
 ['Margem bruta','dre','Parcela da receita líquida que sobra depois do custo das vendas.','R$ 40 mil de lucro bruto para R$ 100 mil de receita líquida representam 40%.','Lucro bruto ÷ receita líquida × 100'],
 ['Despesa operacional','custos','Gasto reconhecido para vender ou administrar a operação, separado do custo dos produtos e serviços vendidos.','Comissões comerciais e despesas administrativas reduzem o resultado operacional.'],
 ['Despesa administrativa','custos','Despesa ligada à gestão e ao suporte da empresa. A classificação depende da função do gasto.','Energia do escritório pode ser administrativa; energia da fábrica pode compor o custo de produção.'],
 ['EBIT / LAJIR','dre','Resultado antes dos juros e dos tributos sobre o lucro. No painel, é o subtotal das operações continuadas antes do resultado financeiro e de IRPJ/CSLL.','Permite observar a operação antes dos efeitos financeiros e dos tributos sobre o lucro.'],
 ['Margem operacional','dre','Resultado operacional antes de financeiro e tributos dividido pela receita líquida.','EBIT de R$ 12 mil e receita líquida de R$ 80 mil resultam em 15%.','EBIT ÷ receita líquida × 100'],
 ['Receita financeira','dre','Juros, rendimentos e outros ganhos financeiros reconhecidos no período. O recebimento do principal de um empréstimo não entra aqui.','O rendimento de uma aplicação é receita financeira; recuperar o valor aplicado não é uma nova receita.'],
 ['Despesa financeira','dre','Juros, encargos e outras despesas financeiras reconhecidas. O principal de uma dívida não é despesa financeira.','Uma prestação de R$ 1.100 pode conter R$ 1.000 de principal e R$ 100 de juros.'],
 ['Resultado financeiro','dre','Diferença entre receitas e despesas financeiras. Pode ser positivo ou negativo.','R$ 500 de rendimentos menos R$ 2 mil de juros = resultado financeiro de −R$ 1.500.','Receitas financeiras − despesas financeiras'],
 ['LAIR','dre','Lucro Antes do Imposto de Renda. Aqui, subtotal antes de IRPJ e CSLL das operações continuadas. Se negativo, há prejuízo antes dos tributos.','Parte do resultado operacional e incorpora o resultado financeiro.'],
 ['IRPJ e CSLL','dre','Tributos sobre o lucro, apurados segundo o regime e as regras aplicáveis. A despesa no DRE pode diferir do pagamento do mês.','Um pagamento de tributo referente a outro período não deve ser simplesmente copiado para a despesa de hoje.'],
 ['Tributo diferido','contabil','Efeito tributário reconhecido em função de diferenças temporárias e outros itens elegíveis. Exige apuração contábil própria.','Pode representar despesa ou benefício no resultado, sem pagamento imediato.'],
 ['Resultado líquido','dre','Lucro ou prejuízo após custos, despesas, resultado financeiro, tributos e demais resultados aplicáveis. Não representa dinheiro disponível para distribuir.','Uma empresa pode ter lucro e pouco caixa por ainda não ter recebido suas vendas.'],
 ['Margem líquida','dre','Parcela da receita líquida que permanece como resultado líquido. Não é a diferença entre entradas e saídas bancárias.','Lucro de R$ 8 mil sobre receita líquida de R$ 100 mil corresponde a 8%.','Resultado líquido ÷ receita líquida × 100'],
 ['EBITDA / LAJIDA','dre','Indicador antes de juros, tributos sobre o lucro, depreciação e amortização. Neste painel é calculado para operações continuadas, a partir do EBIT e da D&A já reconhecida. Não é caixa gerado nem substitui o lucro.','EBIT de R$ 20 mil e D&A de R$ 5 mil já incluída nos custos/despesas resultam em EBITDA de R$ 25 mil.','EBIT das operações continuadas + depreciação e amortização incluídas'],
 ['Margem EBITDA','dre','EBITDA dividido pela receita líquida. Deve usar a mesma base de empresas e períodos do indicador.','EBITDA de R$ 25 mil sobre receita líquida de R$ 100 mil corresponde a 25%.','EBITDA ÷ receita líquida × 100'],
 ['Recebimento','caixa','Entrada de dinheiro referente a venda, adiantamento, empréstimo ou outra origem. A natureza determina o tratamento no DRE.','Receber uma venda de julho em agosto gera caixa em agosto, sem reconhecer a venda outra vez.'],
 ['Pagamento','caixa','Saída de dinheiro. Pode quitar uma despesa, uma dívida ou comprar um ativo, entre outras finalidades.','Pagar uma máquina não significa reconhecer todo o valor como despesa naquele mês.'],
 ['Variação de caixa','caixa','Diferença entre entradas e saídas do período e escopo considerados. Não inclui automaticamente o saldo inicial.','R$ 30 mil de entradas e R$ 24 mil de saídas geram variação positiva de R$ 6 mil.','Entradas − saídas'],
 ['Saldo disponível','caixa','Dinheiro efetivamente disponível nas contas consideradas, depois de conferir saldos, restrições e movimentos.','Somar variações mensais sem saber o saldo inicial não comprova o dinheiro no banco.'],
 ['Fluxo de caixa','caixa','Organização dos movimentos de dinheiro ao longo do tempo. Pode mostrar valores realizados ou uma previsão identificada como cenário.','Uma projeção semanal revela uma falta de dinheiro antes de um recebimento previsto.'],
 ['Caixa operacional','caixa','Movimentos ligados às atividades operacionais. Neste painel a separação é gerencial e depende da classificação das contas.','Recebimentos de clientes e pagamentos operacionais ajudam a observar a rotina financeira.'],
 ['Capital de giro','caixa','Recursos necessários para sustentar o ciclo da operação. Não equivale apenas ao dinheiro no banco.','Estoque e vendas a prazo consomem recursos antes que os clientes paguem.'],
 ['Capital circulante líquido','caixa','Diferença entre ativo circulante e passivo circulante. É uma medida patrimonial, com limites para avaliar a liquidez imediata.','R$ 200 mil de ativos circulantes e R$ 140 mil de passivos circulantes deixam R$ 60 mil.','Ativo circulante − passivo circulante'],
 ['Necessidade de capital de giro','caixa','Recursos presos no ciclo operacional, considerando contas operacionais a receber, estoques e obrigações operacionais. A composição precisa ser definida.','Vender com prazo longo e pagar fornecedores rapidamente costuma aumentar essa necessidade.'],
 ['DSO / prazo de recebimento','caixa','Estimativa do tempo médio para receber clientes. O cálculo deve relacionar contas a receber e vendas a prazo em bases compatíveis.','Receber em 45 dias e pagar antes disso exige financiar parte do ciclo.'],
 ['DPO / prazo de pagamento','caixa','Estimativa do tempo médio para pagar fornecedores. Depende de compras e saldos a pagar compatíveis.','Um prazo maior pode aliviar o caixa, mas deve respeitar contratos e condições comerciais.'],
 ['Giro de estoque','custos','Relaciona o consumo ou custo das vendas ao estoque médio. Mede a renovação do estoque em um período.','Usar compras no lugar de consumo pode distorcer o giro.','Custo das vendas ÷ estoque médio'],
 ['Ciclo financeiro','caixa','Intervalo entre pagar a operação e receber as vendas. Uma aproximação combina prazo de estoque, recebimento e pagamento.','30 dias em estoque + 40 para receber − 25 para pagar = 45 dias.','Prazo de estoque + prazo de recebimento − prazo de pagamento'],
 ['Inadimplência','caixa','Obrigações vencidas e não pagas. Não significa automaticamente que toda a quantia será perdida.','Acompanhe vencimento, dias em atraso, negociações e probabilidade de recuperação.'],
 ['Provisão','contabil','Reconhecimento de obrigação com prazo ou valor incerto quando os critérios contábeis são atendidos. Não é uma reserva de dinheiro em uma conta bancária.','Separar dinheiro para uma compra planejada não cria, por si só, uma provisão contábil.'],
 ['Custo fixo','custos','Custo que tende a não variar com o volume produzido dentro de determinada faixa e horizonte.','O aluguel da fábrica pode permanecer igual mesmo com variação moderada da produção.'],
 ['Custo variável','custos','Custo que acompanha o volume de atividade, conforme o processo produtivo.','O material aplicado em peças vendidas costuma variar com a quantidade produzida.'],
 ['Custo direto','custos','Recurso que pode ser atribuído a um produto, serviço ou O.S. de forma identificável.','Uma chapa registrada para uma O.S. específica pode ser custo direto dessa entrega.'],
 ['Custo indireto','custos','Recurso compartilhado que não é atribuído diretamente a uma única entrega sem um critério de alocação.','Energia compartilhada entre várias máquinas pode exigir medição ou rateio.'],
 ['Rateio','custos','Distribuição de um gasto compartilhado por um critério explícito e consistente.','Horas de máquina podem distribuir um custo fabril quando refletem o consumo dos recursos.'],
 ['Centro de custos','custos','Área ou unidade usada para atribuir e acompanhar gastos. Categoria de despesa e centro de custos são dimensões diferentes.','Energia é a categoria; Produção e Administração podem ser centros. Aqui a primeira visão compara categorias por mês.'],
 ['Margem de contribuição','custos','Receita menos custos e despesas variáveis definidos para a análise. Mostra quanto resta para cobrir os fixos e gerar resultado.','Uma venda líquida de R$ 100 com R$ 60 variáveis contribui R$ 40.','Receita líquida − custos e despesas variáveis'],
 ['Ponto de equilíbrio','custos','Volume de vendas necessário para cobrir custos e despesas dentro das premissas adotadas. Exige separar fixos e variáveis.','Fixos de R$ 30 mil e margem de contribuição de 30% exigem R$ 100 mil de receita na mesma base.','Custos e despesas fixos ÷ margem de contribuição percentual'],
 ['Markup','custos','Fator ou acréscimo aplicado ao custo para formar preço. Não é a mesma coisa que margem sobre a venda.','Custo de R$ 100 com acréscimo de 50% dá preço de R$ 150; a margem sobre esse preço é 33,3%, antes de outras despesas.'],
 ['CAPEX','custos','Investimento em ativos com benefícios futuros, sujeito aos critérios de reconhecimento. O desembolso e o efeito no DRE ocorrem de formas diferentes.','A compra de uma máquina pode afetar o caixa agora e o resultado ao longo da vida útil.'],
 ['OPEX','custos','Expressão gerencial para gastos operacionais. Seu significado e fronteira com investimento devem ser definidos na análise.','Uma assinatura usada na operação geralmente é tratada como despesa conforme seu período de uso.'],
 ['Investimento','caixa','Aplicação de recursos com expectativa de benefício futuro. A classificação depende da natureza: ativo operacional, aplicação financeira ou participação, por exemplo.','A compra de um equipamento não deve ser confundida com juros pagos.'],
 ['Depreciação','contabil','Distribuição do valor depreciável de um ativo tangível ao longo da vida útil estimada, conforme o uso e as regras aplicáveis.','Uma máquina afeta custos ou despesas por depreciação; isso não exige um novo pagamento mensal.'],
 ['Amortização','contabil','Pode indicar a apropriação do valor de um intangível ao resultado ou o pagamento do principal de uma dívida. O contexto muda o significado.','A amortização de um empréstimo reduz o saldo da dívida; não é a amortização somada de volta no EBITDA.'],
 ['Principal de empréstimo','credito','Valor da dívida sem os juros e encargos. Recebê-lo ou devolvê-lo movimenta caixa e obrigações, sem criar receita ou despesa pelo principal.','Em uma parcela de R$ 1.100, se R$ 100 forem juros, os R$ 1.000 restantes amortizam a dívida.'],
 ['Juros simples','credito','Juros calculados sobre o capital inicial, sem incorporar juros anteriores à base. Taxa e tempo devem usar a mesma unidade.','R$ 1.000 a 2% ao mês por três meses geram R$ 60 de juros simples.','J = capital × taxa × tempo'],
 ['Juros compostos','credito','Juros calculados sobre o saldo que incorpora os juros acumulados.','R$ 1.000 a 2% ao mês por três meses chegam a R$ 1.061,21, antes de tarifas e impostos.','Montante = capital × (1 + taxa)^tempo'],
 ['Taxa equivalente','credito','Taxa em outra unidade de tempo que produz o mesmo efeito composto. Não se obtém sempre por multiplicação simples.','2% ao mês equivalem a aproximadamente 26,82% ao ano em capitalização composta.','Taxa anual = (1 + taxa mensal)^12 − 1'],
 ['CET','credito','Custo Efetivo Total de uma operação de crédito, expresso em taxa e considerando os componentes aplicáveis, além dos juros anunciados.','Duas propostas com os mesmos juros podem ter custos diferentes por tarifas, seguros e tributos.'],
 ['Valor presente','credito','Valor hoje de um fluxo futuro descontado pela taxa e pelo prazo escolhidos. As premissas determinam o resultado.','Receber R$ 1.100 em um ano vale R$ 1.000 hoje se a taxa de desconto for 10% ao ano.','VP = valor futuro ÷ (1 + taxa)^tempo'],
 ['VPL','credito','Valor Presente Líquido: soma dos fluxos de um projeto trazidos a valor presente, incluindo o investimento inicial.','Um VPL positivo indica retorno superior à taxa exigida dentro das premissas do cenário.'],
 ['TIR','credito','Taxa que zera o VPL dos fluxos de um projeto. Fluxos com alternância de sinais podem ter múltiplas taxas ou nenhuma solução útil.','Não compare projetos apenas pela TIR sem avaliar tamanho, prazo, risco e VPL.'],
 ['Payback','credito','Tempo necessário para recuperar o investimento pelos fluxos previstos. A versão descontada considera o valor do dinheiro no tempo.','Um retorno em dois anos não informa, sozinho, o lucro total nem o risco do projeto.'],
 ['ROI','credito','Retorno sobre investimento. A definição do ganho, do investimento e do período deve acompanhar o indicador.','Ganho de R$ 20 mil para investimento de R$ 100 mil representa 20%, segundo essa definição.','Ganho líquido atribuível ÷ investimento × 100'],
 ['Pró-labore','contabil','Remuneração pelo trabalho de um sócio na empresa. É diferente de distribuição de lucros e exige tratamento próprio.','Uma retirada de sócio deve ter sua natureza identificada antes de entrar em uma rubrica do DRE.'],
 ['Distribuição de lucros','contabil','Destinação de resultado aos sócios, conforme condições aplicáveis. Não é despesa operacional apenas porque houve saída de dinheiro.','O pagamento de lucros distribuídos afeta o caixa, mas não reduz novamente o lucro operacional do mês.'],
 ['Transferência','caixa','Movimentação entre contas ou empresas. A leitura depende do escopo e da natureza da operação.','Uma transferência entre contas da mesma empresa não gera receita ou despesa; no consolidado, confira as duas pontas.'],
 ['Equivalência patrimonial','contabil','Método que reconhece a participação nos resultados e outras variações de investimentos elegíveis, conforme os critérios contábeis.','O resultado reconhecido pode existir mesmo sem recebimento de dividendos no mês.'],
 ['Operação descontinuada','contabil','Componente classificado como descontinuado conforme critérios contábeis específicos. O resultado líquido é apresentado separadamente quando aplicável.','Encerrar uma atividade pequena não significa automaticamente atender aos critérios de operação descontinuada.'],
 ['Conciliação','contabil','Conferência entre bases e documentos para explicar diferenças e confirmar saldos ou movimentos.','Comparar extratos e registros identifica pagamentos faltantes, duplicados ou classificados incorretamente.'],
 ['Balancete','contabil','Relatório de contas contábeis com saldos e movimentos. Ajuda a conferir a escrituração e preparar demonstrações.','Um balancete revisado pode fornecer dados para preencher a competência, respeitando contas e ajustes.'],
 ['Plano de contas','contabil','Estrutura que organiza lançamentos por natureza. Código igual nem sempre garante significado igual entre empresas ou períodos.','Se uma conta mudou de uso, compare o histórico com a classificação original antes de consolidar.'],
 ['Análise horizontal','dre','Comparação da mesma rubrica entre períodos compatíveis. Pode mostrar diferença absoluta e percentual.','De R$ 100 mil para R$ 110 mil a variação é R$ 10 mil ou 10%; uma base zero não permite esse percentual.'],
 ['Análise vertical','dre','Participação de uma rubrica em uma base do mesmo período. No DRE, a receita líquida costuma ser a referência adotada.','Custos de R$ 40 mil em receita líquida de R$ 100 mil representam 40%.'],
 ['Acumulado','dre','Soma monetária dos meses do intervalo. Margens acumuladas são calculadas a partir dos totais, sem fazer média simples das margens mensais.','Meses sem dados impedem tratar o acumulado como um ano completo.'],
 ['Período parcial','contabil','Período cuja cobertura está incompleta. Pode faltar parte dos dias, empresas, contas ou lançamentos.','Um mês coletado até o dia 10 não deve ser comparado automaticamente com outro mês inteiro.'],
 ['Orçado e realizado','dre','Orçado é a meta ou previsão; realizado é o que foi reconhecido ou movimentado, segundo a base escolhida.','Compare orçamento por competência com resultado por competência, identificando ajustes e mudanças de premissas.'],
 ['Liquidez','caixa','Capacidade de atender obrigações. Pode ser medida por indicadores patrimoniais ou avaliada pelo calendário de caixa, com significados diferentes.','Ter patrimônio alto não garante dinheiro suficiente para pagar uma conta amanhã.']
 ].map(([nome,grupo,definicao,exemplo,formula])=>({nome,grupo,definicao,exemplo,formula}));
 const normal=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
 const buscar=(q='',grupo='todos')=>termos.filter(t=>(grupo==='todos'||t.grupo===grupo)&&normal([t.nome,t.definicao,t.exemplo].join(' ')).includes(normal(q.trim())));
 return {grupos,termos,buscar,normal};
})();
const glossarioUI={busca:'',grupo:'todos'};
function conteudoTermo(t){return `<p>${esc(t.definicao)}</p>${t.formula?`<p class="glossary-formula">${esc(t.formula)}</p>`:''}<div class="glossary-example"><span class="eyebrow">NA PRÁTICA</span><p>${esc(t.exemplo)}</p></div>`;}
function resultadosGlossario(){const ts=GlossarioFinanceiro.buscar(glossarioUI.busca,glossarioUI.grupo);return `<p class="hint" role="status">${ts.length} de ${GlossarioFinanceiro.termos.length} termos · exemplos ilustrativos</p><div class="glossary-grid">${ts.map(t=>`<details class="glossary-item"><summary><span>${esc(t.nome)}<small>${esc(GlossarioFinanceiro.grupos[t.grupo])}</small></span><span aria-hidden="true">＋</span></summary><div class="glossary-body">${conteudoTermo(t)}</div></details>`).join('')||'<p class="empty">Nenhum termo encontrado. Tente outra palavra ou escolha todas as categorias.</p>'}</div>`;}
function renderGlossario(){return `<section class="chart-card"><div class="glossary-head"><span class="glossary-icon" aria-hidden="true">📖</span><div><h2>Finanças em palavras claras</h2><p>Entenda o conceito, veja a conta e reconheça o que muda no seu negócio.</p></div></div><div class="cost-controls"><label>Buscar no glossário<input id="glossarioBusca" type="search" placeholder="Ex.: lucro, EBITDA, juros, custo…" value="${esc(glossarioUI.busca)}"></label><label>Assunto<select id="glossarioGrupo"><option value="todos">Todos os assuntos</option>${Object.entries(GlossarioFinanceiro.grupos).map(([k,v])=>`<option value="${k}" ${glossarioUI.grupo===k?'selected':''}>${esc(v)}</option>`).join('')}</select></label><button id="glossarioLimpar">Limpar busca</button></div><div id="glossarioResultados">${resultadosGlossario()}</div></section><details class="card"><summary>Referências e critérios de leitura</summary><div class="card-body"><p>O glossário explica os conceitos para uso gerencial. As regras e classificações da apuração devem acompanhar a realidade da empresa.</p><p>Demonstrativos e regimes: <a href="https://www.cpc.org.br/Arquivos/Documentos/312_CPC_26_R1_rev%2023.pdf" target="_blank" rel="noopener">CPC 26 — apresentação das demonstrações</a> e <a href="https://www.cpc.org.br/CPC/Documentos-emitidos/Pronunciamentos/Pronunciamento?Id=34" target="_blank" rel="noopener">CPC 03 — fluxos de caixa</a>.</p><p>Indicadores de resultado: <a href="https://conteudo.cvm.gov.br/legislacao/resolucoes/resol156.html" target="_blank" rel="noopener">Resolução CVM 156 — LAJIDA e LAJIR</a>. O indicador deste painel usa operações continuadas e não inclui ajustes adicionais.</p><p>Para aprofundar a gestão: <a href="https://sebrae.com.br/Sebrae/Portal%20Sebrae/Arquivos/ebook_guia_de_planejamento_financeiro.pdf" target="_blank" rel="noopener">Guia de planejamento financeiro — Sebrae</a>.</p></div></details>`;}
function wireGlossario(){
 if($$('glossarioBusca'))$$('glossarioBusca').oninput=e=>{glossarioUI.busca=e.target.value;$$('glossarioResultados').innerHTML=resultadosGlossario();};
 if($$('glossarioGrupo'))$$('glossarioGrupo').onchange=e=>{glossarioUI.grupo=e.target.value;$$('glossarioResultados').innerHTML=resultadosGlossario();};
 if($$('glossarioLimpar'))$$('glossarioLimpar').onclick=()=>{glossarioUI.busca='';glossarioUI.grupo='todos';render();$$('glossarioBusca').focus();};
 document.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>{const t=GlossarioFinanceiro.termos.find(t=>t.nome===b.dataset.term)||GlossarioFinanceiro.buscar(b.dataset.term)[0];if(!t)return;dialog(t.nome,conteudoTermo(t)+'<div class="actions"><button id="abrirGlossario">Explorar o glossário completo →</button></div>');$$('abrirGlossario').onclick=()=>{$$('detailDialog').close();state.view='glossario';render();};});
}
