import fs from 'node:fs';import vm from 'node:vm';import {test} from 'node:test';import assert from 'node:assert/strict';
const c={document:{addEventListener(){},querySelectorAll:()=>[]},localStorage:{getItem:()=>null},structuredClone};vm.createContext(c);
for(const f of ['financeiro.js','graficos.js','dre-modelo.js','demonstrativos.js','glossario.js','cfo-modelo.js','cfo.js','pdf-cfo.js','app.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c);
const F=c.DREFinancas,C=c.DRECFO;
const rec=(values,more={})=>({label:'Ago/2026',company:'Empresa teste',basis:'caixa',origem:'erp',qualidade:{estado:'fechado',ate:'2026-08-31',regra:'v2',escopo:'DRE'},cells:Object.entries(values).map(([code,value])=>({code,value,name:code})),...more});
test('cada fórmula exibida reconcilia o total gerencial no centavo',()=>{
 const codes=[...new Set(Object.values(C.caixa).flat().map(x=>x[0]))];
 for(let i=1;i<=50;i++){const r=rec(Object.fromEntries(codes.map((x,j)=>[x,(i+j)*9.13])));for(const id of Object.keys(C.caixa)){const d=C.decompor(r,id);assert.equal(Math.round(d.value*100),d.partes.reduce((n,x)=>n+Math.round((x.value||0)*100)*x.sinal,0),id);}}
});
test('ausência, zero e fórmula sem totais são distintos',()=>{assert.equal(C.decompor(null,'entradas').value,null);assert.equal(C.decompor(rec({'1':0,'2':0}),'variacao').value,0);assert.equal(C.decompor(rec({'1':100}),'variacao').value,null);assert.equal(C.decompor(rec({'1':100,'2':50}),'2.5').value,null);});
test('prioridades não somam pai e filho, e conservam diferença negativa',()=>{const a=C.analise(rec({'1':100,'2':80,'2.5':100,'2.5.3':100}));assert.equal(a.ranking.length,2);assert.equal(a.residual,-20);assert.equal(a.ranking.reduce((n,x)=>n+x.value,0),80);});
test('meses parciais não recebem ranking de variações nem causas inventadas',()=>{const old=rec({'1':100,'2':80,'2.5':80},{label:'Jul/2026'}),now=rec({'1':20,'2':15,'2.5':15},{qualidade:{estado:'parcial',ate:'2026-08-10'}});assert.equal(C.analise(now,old).variacoes.length,0);assert.equal(C.analise(now,old).comparavel,false);});
test('conta renomeada não recebe diferença automática',()=>{const a=rec({'1':100,'2':80,'2.5':80}),b=rec({'1':90,'2':70,'2.5':70},{label:'Jul/2026'});assert.equal(C.analise(a,b).variacoes[0].delta,10);b.cells.at(-1).name='Outra';assert.equal(C.analise(a,b).variacoes.length,0);});
test('não liga pagamentos a produtos por código semelhante',()=>{const r=rec({'1':100,'2':50},{eventos:[{natureza:'entrada',contaOrigem:'1.1',valor:100},{natureza:'saida',contaOrigem:'2.5',valor:50}]});assert.equal(C.origem(r,'1').eventos.length,1);assert.equal(C.origem(r,'2').eventos.length,1);assert.equal(C.origem(r,'1.1').disponivel,false);assert.equal(C.origem(r,'2.5').eventos.length,0);});
test('cenário de equilíbrio usa margem de contribuição, bloqueia premissas inválidas',()=>{const r=C.sensibilidade({receita:10000,custoVariavel:6000,fixos:2000,meta:1000});assert.equal(r.equilibrio,5000);assert.equal(r.vendaMeta,7500);assert.equal(r.resultado,2000);for(const p of [{receita:0,custoVariavel:0,fixos:1},{receita:100,custoVariavel:100,fixos:1},{receita:100,custoVariavel:-1,fixos:1},{receita:100,custoVariavel:10,fixos:NaN}])assert.equal(C.sensibilidade(p).valido,false);});
test('fórmulas de competência coincidem com todos os subtotais',()=>{const vals=Object.fromEntries(c.DREModelo.campos.map((x,i)=>[x.id,(i+1)*100.13])),r=c.DREModelo.calcular(vals);for(const [id,parts] of Object.entries(C.competencia)){assert.equal(Math.round(r[id]*100),parts.reduce((n,[k,s])=>n+Math.round(r[k]*100)*s,0),id);}});
function stateFixture(){c.fixture=rec({'1':1000,'2':800,'2.5':800,'2.5.3':800});vm.runInContext("state.periodo='Ago/2026';state.records=[fixture];state.D={accounts:[]};state.comparar='';",c);}
test('telas CFO escapam nomes e preservam mês das células clicadas',()=>{stateFixture();c.fixture.cells.at(-1).name='<img src=x onerror=alert(1)>';const html=vm.runInContext('renderCFO(regAtual())+tabelaDRE(dadosDRE())+tabelaCustos()',c);assert.doesNotMatch(html,/<img src=x|NaN|undefined/);assert.match(html,/data-cfo-period="Ago\/2026"/);assert.match(html,/data-cfo-rubrica="entradas"/);});
test('PDF mensal inclui 12 meses, todas as rubricas e lacunas, sem depender do scroll',()=>{stateFixture();const r=vm.runInContext("relatorioCFO({tipo:'anual',base:'caixa',periodo:state.periodo})",c);assert.equal(r.blocos.length,5);assert.ok(r.blocos[0].colunas.includes('Jan/2026'));assert.ok(r.blocos[3].colunas.includes('Dez/2026'));assert.ok(r.blocos[0].linhas.some(row=>row.includes('Não apurado')));});
test('PDF de origem contém todos os movimentos, não apenas os 80 da tela',()=>{stateFixture();c.fixture.eventos=Array.from({length:251},(_,i)=>({natureza:'saida',empresa:'Teste',tituloId:String(i),data:'2026-08-10',valor:1,contaOrigem:'2.5',nomeConta:'Teste'}));const r=vm.runInContext("relatorioCFO({tipo:'origem',code:'2',periodo:state.periodo})",c);assert.equal(r.blocos[0].linhas.length,251);assert.match(r.blocos[0].linhas.at(-1)[1],/250/);});
test('PDF detalhado respeita o filtro da tela',()=>{stateFixture();const r=vm.runInContext("state.consulta='2.5.3';state.tipo='2';relatorioCFO({tipo:'contas',periodo:state.periodo})",c);assert.equal(r.blocos.at(-1).linhas.length,1);assert.equal(r.blocos.at(-1).linhas[0][0],'2.5.3');});

test('composição com valor inválido não produz percentuais de concentração',()=>{const a=C.analise(rec({'1':100,'2':80,'2.1':null,'2.5':40}));assert.equal(a.incompleta,true);assert.equal(a.concentracao,null);assert.ok(a.ranking.every(x=>x.peso==null));});
