import fs from 'node:fs';import vm from 'node:vm';import {test} from 'node:test';import assert from 'node:assert/strict';
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../dre-modelo.js',import.meta.url),'utf8'),ctx);const M=ctx.DREModelo;
const valores=(extra={})=>Object.assign(Object.fromEntries(M.campos.map(c=>[c.id,0])),extra);
test('DRE por competência fecha receita, deduções, lucro e financeiro',()=>{
 const r=M.calcular(valores({produtos:1000,tributosVendas:100,custos:400,administrativas:150,despesasFinanceiras:20,tributosLucro:30,da:50}));
 assert.equal(r.liquida,900);assert.equal(r.bruto,500);assert.equal(r.operacional,350);assert.equal(r.liquido,300);assert.equal(r.ebitda,400);
});
test('D&A já incluída não é descontada novamente do lucro',()=>{const r=M.calcular(valores({produtos:100,custos:40,da:10}));assert.equal(r.liquido,60);assert.equal(r.ebitda,70);});
test('campo ausente propaga ausência e não apura lucro falso',()=>{const r=M.calcular({produtos:100,servicos:0,outrasVendas:0});assert.equal(r.bruta,100);assert.equal(r.liquida,null);assert.equal(r.liquido,null);assert.equal(r.ebitda,null);});
test('benefício tributário e resultado de equivalência aceitam sinais',()=>{const r=M.calcular(valores({produtos:100,equivalencia:-5,tributosDiferidos:-3}));assert.equal(r.operacional,95);assert.equal(r.liquido,98);});
test('valores inválidos e despesa negativa sem natureza de ajuste são rejeitados',()=>{assert.throws(()=>M.calcular({produtos:'100'}));assert.throws(()=>M.calcular({custos:-3}));assert.throws(()=>M.calcular({produtos:Infinity}));});
test('margem anual usa totais, não média das margens mensais',()=>{const r=M.acumulado([{valores:valores({produtos:100,custos:50})},{valores:valores({produtos:900,custos:810})}]);assert.equal(r.liquido,140);assert.ok(Math.abs(r.margemLiquida-14)<1e-10);});
test('mês ausente bloqueia acumulado completo e receita zero não gera percentual',()=>{assert.equal(M.acumulado([{valores:valores({produtos:100})},null]).liquido,null);assert.equal(M.calcular(valores()).margemLiquida,null);});
test('operações descontinuadas não integram o subtotal das continuadas',()=>{const r=M.calcular(valores({produtos:100,descontinuadas:-25}));assert.equal(r.continuadas,100);assert.equal(r.liquido,75);});
const C=ctx.DRECompetencia;
const registro=()=>({label:'Set/2026',company:'Empresa exemplo',fonte:'Balancete de teste',valores:valores({produtos:100}),revisao:'revisao-teste',revisadoEm:'2026-09-09T12:00:00Z'});
test('salvar competência preserva regras, permissões e outros meses na versão recém-lida',async()=>{const other={label:'Ago/2026',valores:{produtos:42}};let sent;const api=async(a,p)=>a==='getCfg'?{ok:true,cfg:{regras:{nova:1},permissoes:{p:'admin'},demonstrativosCompetencia:{versao:1,meses:{Ago_2026:other}}},atualizadoEm:'fresh'}:(sent=p,{ok:true,atualizadoEm:'saved'});const r=await C.salvar({api,admin:true,id:'Set_2026',original:null,registro:registro()});assert.equal(sent.baseAtualizadoEm,'fresh');assert.equal(r.cfg.regras.nova,1);assert.equal(r.cfg.permissoes.p,'admin');assert.equal(r.cfg.demonstrativosCompetencia.meses.Ago_2026,other);assert.equal(r.cfg.demonstrativosCompetencia.meses.Set_2026.valores.produtos,100);});
test('mudança concorrente no mesmo mês interrompe a gravação',async()=>{let writes=0;const api=async a=>a==='getCfg'?{ok:true,cfg:{demonstrativosCompetencia:{meses:{Set_2026:{revisao:'outra'}}}}}:(writes++,{ok:true});await assert.rejects(C.salvar({api,admin:true,id:'Set_2026',original:null,registro:registro()}),/mudou/);assert.equal(writes,0);});
test('permissão de leitura não tenta gravar competência',async()=>{let calls=0;await assert.rejects(C.salvar({api:async()=>calls++,admin:false,id:'Set_2026',original:null,registro:registro()}),/administração/);assert.equal(calls,0);});
test('conflito atômico e erro de servidor nunca são sucesso',async()=>{for(const result of [{conflito:true},{erro:'falha'}]){const api=async a=>a==='getCfg'?{ok:true,cfg:{},atualizadoEm:'v1'}:result;await assert.rejects(C.salvar({api,admin:true,id:'Set_2026',original:null,registro:registro()}));}});
test('resposta perdida não repete revisão já salva',async()=>{let writes=0;const reg=registro(),cfg={demonstrativosCompetencia:{meses:{Set_2026:reg}}};const api=async a=>a==='getCfg'?{ok:true,cfg,atualizadoEm:'v1'}:(writes++,{ok:true});const r=await C.salvar({api,admin:true,id:'Set_2026',original:null,registro:reg});assert.equal(r.cfg,cfg);assert.equal(writes,0);});
test('edição mantém histórico limitado e não modifica registro anterior',async()=>{const old={...registro(),revisao:'anterior',historico:[{revisao:'a'},{revisao:'b'},{revisao:'c'}]},copy=JSON.stringify(old);const api=async a=>a==='getCfg'?{ok:true,cfg:{demonstrativosCompetencia:{versao:1,meses:{Set_2026:old}}},atualizadoEm:'v1'}:{ok:true};const r=await C.salvar({api,admin:true,id:'Set_2026',original:old,registro:registro()});assert.equal(r.cfg.demonstrativosCompetencia.meses.Set_2026.historico.length,3);assert.equal(JSON.stringify(old),copy);});
function tela(){const c={document:{addEventListener(){},querySelectorAll:()=>[]},localStorage:{getItem:()=>null}};vm.createContext(c);for(const f of ['financeiro.js','graficos.js','dre-modelo.js','demonstrativos.js','glossario.js','cfo-modelo.js','cfo.js','pdf-cfo.js','app.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c);vm.runInContext("state.D={accounts:[]};state.periodo='Set/2026';",c);return c;}
test('ambos os demonstrativos renderizam 12 meses sem inventar números em mês vazio',()=>{const c=tela();for(const base of ['caixa','competencia']){const html=vm.runInContext(`dreUI.base='${base}';renderDRE()`,c);assert.match(html,/Jan\/2026/);assert.match(html,/Dez\/2026/);assert.doesNotMatch(html,/NaN|undefined/);assert.match(html,/Não apurado/);}});
test('acumulado por competência bloqueia empresas diferentes',()=>{const c=tela();c.months={Jan_2026:{company:'A',valores:valores({produtos:10})},Fev_2026:{company:'B',valores:valores({produtos:20})}};const r=vm.runInContext("state.periodo='Fev/2026';dreUI.base='competencia';state.cfg={demonstrativosCompetencia:{meses:months}};dadosDRE()",c);assert.equal(r.mesmoEscopo,false);assert.equal(r.soma.liquido,undefined);});
test('glossário busca sem acentos, filtra assuntos e cobre toda a ajuda do DRE',()=>{const c=tela();const out=vm.runInContext("({count:GlossarioFinanceiro.termos.length,busca:GlossarioFinanceiro.buscar('depreciacao'),cats:GlossarioFinanceiro.buscar('','credito'),missing:[...DREModelo.linhas,...linhasCaixa].filter(r=>!GlossarioFinanceiro.termos.some(t=>t.nome===r.termo))})",c);assert.ok(out.count>=70);assert.ok(out.busca.some(t=>t.nome==='Depreciação'));assert.ok(out.cats.every(t=>t.grupo==='credito'));assert.equal(out.missing.length,0);});
test('backup preserva competência e exclui segredos',()=>{const c=tela();const r=vm.runInContext("configSegura({demonstrativosCompetencia:{versao:1,meses:{}},permissoes:{},accessToken:'x'})",c);assert.deepEqual(Object.keys(r),['demonstrativosCompetencia']);});
