import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {test} from 'node:test';
function context(){const c={structuredClone,document:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},navigator:{onLine:true}};vm.createContext(c);for(const f of ['financeiro.js','graficos.js','dre-modelo.js','demonstrativos.js','cfo-modelo.js','cfo.js','app.js','gestao.js','pdf-cfo.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c);c.run=s=>vm.runInContext(s,c);c.run("state.periodo='Fev/2026';state.permissoes.admin=true;state.cfg={};");return c;}
test('acumulado interrompe em mudança de escopo e no mês selecionado',()=>{const c=context();const values=c.run(`state.records=['Jan','Fev','Mar'].map((m,i)=>({label:m+'/2026',company:i===0?'Impresilk':'Impresilk + Universo',basis:'Caixa',cells:[{code:'1',value:100}]}));acumularAno('1').map(x=>x.acumulado)`);assert.equal(values[0],null);assert.equal(values[1],null);assert.equal(values[2],null);c.run("state.records.forEach(r=>r.company='Impresilk + Universo')");const r=c.run("acumularAno('1')");assert.equal(r[1].acumulado,200);assert.equal(r[2].acumulado,null);});
test('filtro de contas compartilhado conserva hierarquia, acentos e zero',()=>{const c=context();const rows=c.run(`state.consulta='agua';state.tipo='2';state.grupo='2.5';filtrarContas({cells:[{code:'2.5.1',name:'Água',value:0},{code:'20.5.1',name:'Água',value:10},{code:'2.6.1',name:'Água',value:20}]})`);assert.equal(rows.length,1);assert.equal(rows[0].value,0);});
test('salvar orçamento mantém competência e regras e registra versão',async()=>{const c=context();let saved;c.api=async(action,b)=>action==='getCfg'?{ok:true,cfg:{demonstrativosCompetencia:{preservado:true},gestao:{outro:{valor:1}}},atualizadoEm:'a'}:(saved=b,{ok:true,atualizadoEm:'b'});await c.run("salvarGestao('orcamento:Fev_2026',{entradas:100,saidas:80})");assert.equal(saved.baseAtualizadoEm,'a');assert.equal(saved.cfg.demonstrativosCompetencia.preservado,true);assert.equal(saved.cfg.gestao.outro.valor,1);assert.equal(saved.cfg.gestao.historico.length,1);assert.equal(c.run("state.cfg.gestao['orcamento:Fev_2026'].entradas"),100);});
test('alteração concorrente conserva edição e não sobrescreve nuvem',async()=>{const c=context();let writes=0;c.api=async(action)=>{if(action==='setCfg')writes++;return {ok:true,cfg:{gestao:{plano:{saldo:300}}}};};await assert.rejects(c.run("salvarGestao('plano',{saldo:100},null)"),/mudou na nuvem/);assert.equal(writes,0);});
test('erro de gravação não apresenta estado não salvo como confirmado',async()=>{const c=context();c.api=async a=>a==='getCfg'?{ok:true,cfg:{}}:{erro:'indisponível'};await assert.rejects(c.run("salvarGestao('alertas',{horas:24})"),/não confirmada/);assert.equal(c.run('state.cfg.gestao'),undefined);});
test('leitor não altera planejamento nem chama servidor para gravar',async()=>{const c=context();c.run('state.permissoes.admin=false');c.api=()=>{throw Error('não deve chamar');};await assert.rejects(c.run("salvarGestao('plano',{saldo:100})"),/administrativo/);});
test('ação conserva histórico de resolução e reabertura, sem mudar meses',async()=>{const c=context();let cfg={};c.api=async(a,b)=>a==='getCfg'?{ok:true,cfg:structuredClone(cfg),atualizadoEm:'x'}:(cfg=structuredClone(b.cfg),{ok:true,atualizadoEm:'x'});await c.run("salvarGestao('acao:Fev_2026:1',{titulo:'Conferência',situacao:'Resolvida',notas:'Conferido'})");await c.run("salvarGestao('acao:Fev_2026:1',{titulo:'Conferência',situacao:'Em análise',notas:'Nova evidência'})");assert.equal(cfg.gestao.historico.length,2);assert.equal(cfg.gestao.historico[1].anterior.situacao,'Resolvida');assert.equal(c.run('state.records.length'),0);});
test('competência de empresas diferentes não recebe variação',()=>{const c=context();const html=c.run(`celulaComparativo({competencia:true,ate:2,cols:[{comp:{company:'A'}},{comp:{company:'B'}}],valores:[{liquida:100,bruto:20},{liquida:100,bruto:40}]},{id:'bruto',tipo:'result'})`);assert.doesNotMatch(html,/\+100/);});
test('origem gerencial exige versão, vínculo exato e total conciliado',()=>{const c=context();const r={cells:[{code:'2.5',value:100}],trilhaClassificacao:{versao:'caixa-trilha-1',de:'2026-09-01',ate:'2026-09-30'},eventos:[{natureza:'saida',contaGerencial:'2.5.1',regraClassificacao:'caixa-trilha-1',valor:40},{natureza:'saida',contaGerencial:'2.5.2',regraClassificacao:'caixa-trilha-1',valor:60},{natureza:'saida',contaGerencial:'2.50',regraClassificacao:'caixa-trilha-1',valor:99}]};c.r=r;assert.equal(c.run("DRECFO.origem(r,'2.5').eventos.length"),2);r.eventos[1].valor=59;assert.equal(c.run("DRECFO.origem(r,'2.5').disponivel"),false);r.eventos[1].valor=60;delete r.trilhaClassificacao;assert.equal(c.run("DRECFO.origem(r,'2.5').disponivel"),false);});

test('PDF de contas contém só o recorte, filtros e comparação, sem relatório geral',()=>{const c=context();const r=c.run(`state.consulta='Cemig';state.tipo='2';state.grupo='todos';state.comparar='Jan/2026';state.records=['Jan','Fev'].map((m,i)=>({label:m+'/2026',company:'Impresilk',basis:'Caixa',cells:[{code:'1',name:'Entradas',value:1000},{code:'2',name:'Saídas',value:800},{code:'2.5.3',name:'Cemig',value:100+i*20},{code:'2.5.4',name:'Água',value:50}]}));relatorioCFO({tipo:'contas'})`);assert.equal(r.blocos.length,1);assert.equal(r.blocos[0].linhas.length,1);assert.equal(r.blocos[0].linhas[0][1],'Cemig');assert.equal(r.blocos[0].linhas[0].length,5);assert.ok(r.notas.some(n=>n.includes('busca Cemig')&&n.includes('saídas')));assert.doesNotMatch(JSON.stringify(r.blocos),/Água|Retrato do período|Onde investigar/);});
