// Integração local isolada: nenhuma chamada chega ao servidor de produção.
import {chromium} from '/Users/leonardopereira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const dir='entregas/revisao-v91';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox']});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let cfg={},version='0',writes=0;
// Como o jsonb do Postgres: chaves por tamanho e depois por bytes (em parametros e gestao, onde a comparação já é canônica).
const jsonb=v=>Array.isArray(v)?v.map(jsonb):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort((a,b)=>a.length-b.length||(a<b?-1:a>b?1:0)).map(k=>[k,jsonb(v[k])])):v;
const records=['Ago','Set'].map((m,i)=>({id:m+'_2026',label:m+'/2026',company:'Impresilk + Universo',basis:'Caixa gerencial',origem:'erp',atualizadoEm:'2026-10-08T15:00:00Z',qualidade:{ate:i?'2026-09-30':'2026-08-31',estado:'aguardando-conferencia',regra:'caixa-v2',escopo:'compõe DRE'},cells:[{code:'1',name:'Entradas',value:1000+i*200},{code:'2',name:'Saídas',value:800+i*100},{code:'2.5',name:'Fixas',value:100+i*100},{code:'2.5.1',name:'Água',value:0},{code:'2.5.2',name:'Cemig',value:100+i*100}],pendencias:Array.from({length:25},(_,j)=>({tipo:j%2?'Classificação':'Cobertura',texto:'Conferir registro '+j,conta:'2.5',valor:10})),eventos:[]}));
await ctx.route('https://heveemylixartyijxewh.supabase.co/**',async route=>{let b={};try{b=route.request().postDataJSON()||{};}catch{}let r={ok:true};if(b.action==='permissions')r={ok:true,permissoes:{leitura:true,edicao:true,admin:true}};if(b.action==='list')r={ok:true,itens:records,nextOffset:null};if(b.action==='getCfg')r={ok:true,cfg:{...cfg,...(cfg.parametros&&{parametros:jsonb(cfg.parametros)}),...(cfg.gestao&&{gestao:jsonb(cfg.gestao)})},atualizadoEm:version};if(b.action==='setCfg'){assert.equal(b.baseAtualizadoEm,version);cfg=b.cfg;version=String(+version+1);writes++;r={ok:true,atualizadoEm:version};}if(b.action==='coletaStatus')r={ok:true,coleta:{estado:'concluida'}};if(b.action==='indicadores')r={ok:false,erro:'Sem fonte nesta fixture'};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(r)});});
await ctx.addInitScript(()=>{localStorage.setItem('impresilk_dre_cracha','fixture.'+btoa(JSON.stringify({sub:'teste'}))+'.fixture');const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('dre_v2_data:'))throw new DOMException('Cache cheio','QuotaExceededError');return set.call(this,k,v);};});
try{
 await page.goto('http://127.0.0.1:8793/#tela=inicio&mes=Set%2F2026&comparar=Ago%2F2026');await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();
 assert.match(await page.locator('.cards').first().innerText(),/1\.200,00/);assert.match(await page.locator('#syncState').innerText(),/sem cópia offline/);assert.equal(await page.locator('#viewTabs button').count(),14);assert.equal(await page.locator('#viewTabs details.nav-grupo').count(),4);
 for(const view of ['inicio','dre','caixa','indicadores','detalhe','conferencia']){
  await page.locator('[data-view="'+view+'"]').click();assert.equal(await page.locator('#monthChips button').count(),12);
  await page.locator('#monthChips [data-period="Ago/2026"]').click();assert.equal(await page.locator('#monthChips [aria-pressed=true]').getAttribute('data-period'),'Ago/2026');assert.match(await page.locator('#footMeta').innerText(),/Ago\/2026/);
  await page.locator('#monthChips [data-period="Set/2026"]').click();assert.equal(await page.locator('#monthChips [aria-pressed=true]').getAttribute('data-period'),'Set/2026');
 }
 await page.locator('[data-view="inicio"]').click();await page.locator('#periodCompare summary').click();await page.locator('#compareSelect').selectOption('Ago/2026');await page.locator('#periodCompare summary').click();assert.match(await page.locator('#compareSummary').innerText(),/Ago\/2026/);
 await page.screenshot({path:dir+'/resumo-desktop.png',fullPage:true});assert.ok((await page.locator('.finance-kpis').boundingBox()).height<100);assert.ok((await page.locator('.cfo-intro').boundingBox()).y>(await page.locator('.dashboard-grid').boundingBox()).y);
 const dashboardCSV=page.waitForEvent('download');await page.locator('#pageSheet').click();await (await dashboardCSV).saveAs(dir+'/dashboard.csv');assert.match(await fs.readFile(dir+'/dashboard.csv','utf8'),/1.200,00/);
 await page.locator('#gestaoPlanejamento').click();await page.locator('[name="entradas"]').fill('1500');await page.locator('[name="saidas"]').fill('1000');await page.locator('[name="fonte"]').fill('Planejamento isolado de teste');await page.getByRole('button',{name:'Salvar orçamento',exact:true}).click();await page.locator('#detailDialog').waitFor({state:'hidden'});assert.equal(cfg.gestao['orcamento:Set_2026'].entradas,1500);
 await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();await page.getByText('Mesmo mês do ano anterior e orçamento',{exact:true}).click();assert.match(await page.locator('.management-panel').innerText(),/1\.500,00/);
 await page.locator('[data-view="detalhe"]').first().click();assert.equal(await page.locator('.plano-list .plano-account:visible').count(),2);await page.locator('[data-plano-toggle="2"]').click();assert.equal(await page.locator('[data-plano-toggle="2.5"]').isVisible(),true);await page.locator('#planoCollapse').click();assert.equal(await page.locator('.plano-list .plano-account:visible').count(),2);await page.locator('#planoSidebarToggle').click();assert.equal(await page.locator('#planoSidebar').isVisible(),false);await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();assert.equal(await page.locator('#planoSidebar').isVisible(),false);await page.locator('#planoSidebarToggle').click();await page.locator('#searchAccounts').fill('cemig');await page.locator('#accountType').selectOption('2');const dlPromise=page.waitForEvent('download');await page.locator('#exportAccounts').click();const dl=await dlPromise;await dl.saveAs(dir+'/contas-filtradas.csv');const csv=await fs.readFile(dir+'/contas-filtradas.csv','utf8');assert.match(csv,/Cemig/);assert.doesNotMatch(csv,/Água|Entradas;1200/);await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();assert.equal(await page.locator('#searchAccounts').inputValue(),'cemig');
 await page.locator('.plano-list [data-plano-select="2.5.2"]').click();assert.equal(await page.locator('.plano-matrix thead th').count(),13);assert.equal(await page.locator('.plano-comparisons tbody tr').count(),12);assert.match(await page.locator('.plano-dashboard').innerText(),/aumentou R\$\s100,00/);await page.locator('[data-plano-tab="planilha"]').click();assert.match(await page.locator('.plano-comparisons').innerText(),/100,00/);await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();assert.equal(await page.locator('.plano-list [aria-pressed=true]').count(),1);await page.screenshot({path:dir+'/plano-contas-desktop-v96.png',fullPage:true});assert.match(await page.locator('.plano-dashboard').innerText(),/100,00/);await page.locator('[data-plano-tab="planilha"]').click();assert.equal(await page.locator('.plano-matrix').isVisible(),true);await page.locator('[data-plano-tab="dashboard"]').click();await page.locator('#planoSidebarToggle').click();assert.equal(await page.locator('#planoSidebar').isVisible(),false);
 const pdfP=page.waitForEvent('download');await page.locator('#cfoPDF').click();await (await pdfP).saveAs(dir+'/contas-filtradas.pdf');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/plano-contas-mobile-v96.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1440,height:1000});
 await page.locator('[data-view="glossario"]').click();await page.locator('#glossarioBusca').fill('EBITDA');const glossCSV=page.waitForEvent('download');await page.locator('#pageSheet').click();await (await glossCSV).saveAs(dir+'/glossario.csv');assert.match(await fs.readFile(dir+'/glossario.csv','utf8'),/EBITDA/);
 await page.locator('[data-view="dre"]').click();assert.equal(await page.locator('.dre-compact').count(),1);assert.equal(await page.locator('#dreMesAtual').count(),0);assert.ok((await page.locator('.dre-compact tbody tr td:nth-child(3)').allTextContents()).every(x=>x==='—'));await page.locator('summary',{hasText:'Movimento de caixa'}).click();await page.locator('[data-dre-visao="ano"]').click();assert.equal(await page.locator('.dre-movimento').evaluate(d=>d.open),true,'o movimento continua aberto depois de trocar a visão');assert.equal(await page.locator('.dre-table').count(),1);assert.equal(await page.locator('#dreMesAtual').count(),1);await page.locator('[data-dre-visao="mes"]').click();const pdfD=page.waitForEvent('download');await page.locator('#drePrint').click();await (await pdfD).saveAs(dir+'/dre-mensal.pdf');
 // Competência: preencher, revisar, persistir e reabrir, apenas no servidor interceptado.
 await page.locator('[data-dre-base="competencia"]').click();assert.equal(await page.locator('#editarCompetencia').isVisible(),true);await page.locator('#editarCompetencia').click();
 await page.locator('[name="company"]').fill('Impresilk + Universo');await page.locator('[name="fonte"]').fill('Apuração sintética isolada');await page.locator('[name="produtos"]').fill('1000');await page.locator('[name="custos"]').fill('400');await page.locator('#competenciaZeros').click();await page.getByRole('button',{name:'Revisar valores antes de salvar',exact:true}).click();await page.locator('#competenciaConfirmar').check();await page.locator('#competenciaSalvar').click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 assert.equal(cfg.demonstrativosCompetencia.meses.Set_2026.valores.produtos,1000);await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();assert.match(await page.locator('.finance-kpis').innerText(),/600,00/);assert.match(await page.locator('.dre-coverage').innerText(),/1 de 12/);
 await page.locator('[data-dre-base="caixa"]').click();assert.match(await page.locator('#pageContent .metric-param').first().innerText(),/Vendas/,'DRE Simples abre a base de caixa');await page.locator('summary',{hasText:'Contas registradas'}).click();assert.match(await page.locator('.source-grid').innerText(),/Fixas/);const sourceCSV=page.waitForEvent('download');await page.locator('#dreContasCSV').click();await (await sourceCSV).saveAs(dir+'/contas-dre-v98.csv');assert.match(await fs.readFile(dir+'/contas-dre-v98.csv','utf8'),/200,00/);
 await page.locator('[data-view="caixa"]').click();await page.getByText('Planejar as próximas 13 semanas',{exact:true}).click();await page.locator('#planSaldo').fill('5000');await page.locator('#planAdicionar').click();await page.locator('[name="descricao"]').fill('Compromisso isolado');await page.locator('[name="valor"]').fill('1500');await page.getByRole('button',{name:'Adicionar à simulação',exact:true}).click();await page.locator('#planSalvar').click();await page.locator('#planEstado').filter({hasText:'Confirmado na nuvem'}).waitFor();assert.equal(cfg.gestao.plano.movimentos.length,1);
 await page.reload();await page.locator('#syncState').filter({hasText:'Dados aplicados'}).waitFor();await page.getByText('Planejar as próximas 13 semanas',{exact:true}).click();assert.equal(await page.locator('#planSaldo').inputValue(),'5000');assert.match(await page.locator('#planMovimentos').innerText(),/Compromisso isolado/);
 await page.locator('[data-view="conferencia"]').click();assert.equal(await page.locator('.review-row').count(),20);await page.locator('#pendTipo').selectOption('Classificação');assert.equal(await page.locator('.review-row').count(),12);await page.locator('[data-pend-key]').first().click();await page.locator('[name="responsavel"]').fill('Pessoa de teste');await page.locator('[name="prazo"]').fill('2026-10-20');await page.locator('[name="situacao"]').selectOption('Resolvida');await page.locator('[name="notas"]').fill('Evidência de teste isolado');await page.getByRole('button',{name:'Salvar revisão',exact:true}).click();await page.locator('#detailDialog').waitFor({state:'hidden'});
 await page.locator('[data-pend-key]').first().click();assert.equal(await page.locator('[name="situacao"]').inputValue(),'Resolvida');await page.locator('[name="situacao"]').selectOption('Em análise');await page.getByRole('button',{name:'Salvar revisão',exact:true}).click();await page.locator('#detailDialog').waitFor({state:'hidden'});assert.ok(cfg.gestao.historico.some(h=>h.anterior?.situacao==='Resolvida'));
 // Parâmetros: número brasileiro, segunda gravação na mesma sessão (jsonb reordena) e rascunho que sobrevive ao redesenho.
 await page.locator('[data-view="parametros"]').click();const mesParam=await page.evaluate(()=>paramMesChave(state.periodo));const fu=page.locator('form[data-param-form="simples"][data-empresa="universo"]');
 await fu.locator('input[name="rbt12"]').fill('1.200.000,00');await fu.locator('input[name="aliquota"]').fill('7,45');await fu.locator('button[type="submit"]').click();await page.locator('#toast',{hasText:'Simples da Universo'}).waitFor();
 assert.equal(cfg.parametros.simples[mesParam].universo.rbt12,1200000,'1.200.000,00 vira 1.200.000, não 1,2');assert.equal(cfg.parametros.simples[mesParam].universo.aliquota,7.45);
 await page.waitForFunction(()=>document.activeElement?.closest?.('form[data-empresa="universo"]')&&document.activeElement.type==='submit',null,{timeout:2000});
 const fi=page.locator('form[data-param-form="simples"][data-empresa="impresilk"]');await fi.locator('input[name="rbt12"]').fill('2.000.000,00');
 await fu.locator('input[name="aliquota"]').fill('7,5');await fu.locator('button[type="submit"]').click();await page.locator('#toast',{hasText:'Simples da Universo'}).waitFor();await page.waitForTimeout(200);
 assert.equal(cfg.parametros.simples[mesParam].universo.aliquota,7.5,'segunda gravação sem conflito falso');assert.equal(await fi.locator('input[name="rbt12"]').inputValue(),'2.000.000,00','o que foi digitado na Impresilk sobrevive');assert.equal(await fi.locator('.param-pendente').isVisible(),true);
 await fi.locator('[data-param-descartar]').click();assert.equal(await fi.locator('input[name="rbt12"]').inputValue(),'');assert.equal(cfg.parametros.simples[mesParam].impresilk,undefined,'descartar não grava');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#viewTabs').isVisible(),false,'Menu fechado no celular');await page.locator('#menuToggle').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#menuToggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('#menuToggle').getAttribute('aria-expanded'),'false','Esc fecha o menu');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.evaluate(()=>document.activeElement?.id),'menuToggle','Esc devolve o foco ao Menu');await page.keyboard.press('Enter');await page.locator('#viewTabs').waitFor({state:'visible'});await page.locator('[data-view="giro"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.activeElement?.id==='pageTitle',null,{timeout:2000}).catch(()=>{});assert.equal(await page.evaluate(()=>document.activeElement?.id),'pageTitle','Foco vai ao título da tela escolhida');await page.locator('#menuToggle').click();await page.locator('[data-view="inicio"]').click();assert.equal(await page.locator('#viewTabs').isVisible(),false,'Menu fecha ao escolher a tela');await page.screenshot({path:dir+'/resumo-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok((await page.locator('.cards .metric strong').first().boundingBox()).y<844,'Primeiro valor aparece sem rolar no celular');
 await page.locator('#menuToggle').click();await page.locator('[data-view="dre"]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:dir+'/dre-mobile.png',fullPage:true});
 await page.goBack();assert.match(await page.locator('#pageTitle').innerText(),/Dashboard/);assert.deepEqual(errors,[]);assert.ok(writes>=4);console.log('OK: atualização com quota, 14 telas no menu em 4 grupos, orçamento compartilhado, filtros e CSV/PDF, DRE mensal/anual, projeção persistida, ações com histórico, recarga, voltar e celular. '+writes+' gravações apenas interceptadas localmente.');
}catch(e){await page.screenshot({path:dir+'/falha.png',fullPage:true});await fs.writeFile(dir+'/falha.txt',await page.locator('body').innerText());throw e;}finally{await fs.writeFile(dir+'/errors.json',JSON.stringify(errors));await browser.close();}
