import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {test} from 'node:test';
function ctx(){const c={structuredClone,document:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},navigator:{onLine:true}};vm.createContext(c);for(const f of ['financeiro.js','graficos.js','dre-modelo.js','demonstrativos.js','cfo-modelo.js','cfo.js','app.js','gestao.js','plano-contas.js'])vm.runInContext(fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),c);c.run=s=>vm.runInContext(s,c);c.run(`state.periodo='Set/2026';state.consulta='';state.tipo='todos';state.grupo='todos';state.records=['Ago','Set'].map((m,i)=>({label:m+'/2026',company:'Impresilk + Universo',basis:'Caixa',origem:'erp',qualidade:{ate:i?'2026-09-30':'2026-08-31',estado:'aguardando-conferencia',regra:'caixa-v2',escopo:'compõe DRE'},cells:[{code:'1',name:'Entradas',value:1000},{code:'2',name:'Saídas',value:500},{code:'2.5.1',name:'Copasa',value:0},{code:'2.5.3',name:'Cemig',value:100+i*50},...(i?[]:[{code:'2.8.1',name:'Serviço antigo',value:20}])]}));`);return c;}
test('catálogo reúne todos os meses, tipos e conta ausente no atual',()=>{const c=ctx();assert.equal(c.run('contextoPlano().catalogo.length'),5);assert.equal(c.run("planoValor(state.records[1],'2.8.1')"),null);assert.equal(c.run("planoValor(state.records[1],'2.5.1')"),0);});
test('água localiza Copasa e energia localiza Cemig sem criar registros',()=>{const c=ctx();assert.equal(c.run("state.consulta='água';contextoPlano().rows[0].name"),'Copasa');assert.equal(c.run("state.consulta='energia';contextoPlano().rows[0].name"),'Cemig');assert.equal(c.run('state.records[0].cells.length'),5);});
test('seleção respeita fronteiras de código e todos os filtros',()=>{const c=ctx();assert.equal(c.run("state.contaSelecionada='2.5';contextoPlano().rows.length"),2);assert.equal(c.run("state.tipo='1';contextoPlano().rows.length"),0);});
test('comparação mês a mês preserva zero, ausência e mudança de empresa ou nome',()=>{const c=ctx();assert.equal(c.run("PlanoContas.comparacao(state.records[1],state.records[0],'2.5.3').delta"),50);assert.equal(c.run("PlanoContas.comparacao(state.records[1],state.records[0],'2.5.1').percentual"),null);assert.equal(c.run("state.records[1].company='Outra';PlanoContas.comparacao(state.records[1],state.records[0],'2.5.3').permitida"),false);c.run("state.records[1].company=state.records[0].company;state.records[1].cells[3].name='Outra conta'");assert.equal(c.run("PlanoContas.comparacao(state.records[1],state.records[0],'2.5.3').permitida"),false);});
test('CSV exporta 12 meses, nomes originais e critérios apenas da seleção',()=>{const c=ctx();c.run("state.consulta='cemig'");const rows=c.run('linhasCSVPlano(contextoPlano())');assert.equal(rows[6].length,17);assert.equal(rows[6][1],'Código no Mubisys');assert.equal(rows[7][12],'100,00');assert.equal(rows[7][13],'150,00');assert.equal(rows[7][5],'Não informado');assert.doesNotMatch(JSON.stringify(rows),/Copasa|Serviço antigo/);assert.equal(rows.length,23);});
test('cores de entradas e saídas preservam o sentido de estornos',()=>{const c=ctx();assert.equal(c.run("planoTom('1.2',100)"),'tom-entra');assert.equal(c.run("planoTom('2.5',100)"),'tom-sai');assert.equal(c.run("planoTom('2.5',-100)"),'tom-entra');assert.equal(c.run("planoTom('2.5',null)"),'');});

test('busca de água não confunde aguardando com água ou Copasa',()=>{const c=ctx();assert.equal(c.run("state.records[0].cells.push({code:'1.99',name:'Produtos aguardando classificação',value:10});state.consulta='água';contextoPlano().rows.length"),1);});

test('árvore reúne ascendentes da busca e não confunde prefixos de códigos',()=>{const c=ctx();const roots=c.run("PlanoContas.arvore([{code:'2',name:'Saídas'},{code:'2.5',name:'Fixas'},{code:'2.5.3',name:'Cemig'},{code:'2.50',name:'Outro'}],[{code:'2.5.3'}])");assert.equal(roots.length,1);assert.equal(roots[0].children[0].code,'2.5');assert.equal(roots[0].children[0].children[0].code,'2.5.3');});
test('dashboard compara o valor da conta, sem somar suas subcontas',()=>{const c=ctx();c.run("state.contaSelecionada='2';state.comparar='Ago/2026'");const html=c.run('dashboardPlano(contextoPlano())');assert.match(html,/500,00/);assert.doesNotMatch(html,/650,00/);assert.match(html,/ficou estável/);assert.match(html,/Composição do mês/);});
test('dashboard preserva ausência e bloqueia mudança de escopo',()=>{const c=ctx();c.run("state.contaSelecionada='2.8.1';state.comparar='Ago/2026'");let html=c.run('dashboardPlano(contextoPlano())');assert.match(html,/Não informado/);assert.match(html,/Abrir último registro: Ago\/2026/);c.run("state.contaSelecionada='2.5.3';state.records[1].company='Outra'");html=c.run('dashboardPlano(contextoPlano())');assert.match(html,/Não comparável/);assert.doesNotMatch(html,/aumentou/);});
test('atalhos só apontam para contas existentes e painel inicia recolhido por níveis',()=>{const c=ctx();const html=c.run('renderPlanoContas()');assert.match(html,/⚡/);assert.match(html,/💧/);assert.doesNotMatch(html,/👥/);assert.match(html,/class="plano-children" hidden/);assert.match(html,/📊 Dashboard/);assert.match(html,/📋 Planilha e comparativos/);});
test('atalhos escolhem despesas principais, sem confundir aluguel recebido ou insumos de máquina',()=>{const c=ctx();c.run("state.records[1].cells.push({code:'1.3.1',name:'Aluguel',value:100},{code:'2.5.2',name:'Aluguel lote',value:500},{code:'2.6.3.1',name:'Materiais/insumos',value:200},{code:'2.12',name:'Materiais e Insumos',value:800},{code:'2.1.1',name:'Salário',value:null},{code:'2.1.4',name:'Salário',value:1000})");const html=c.run('atalhosPlano(contextoPlano())');assert.match(html,/data-plano-quick="2.5.2"/);assert.match(html,/data-plano-quick="2.12"/);assert.match(html,/data-plano-quick="2.1.4"/);assert.doesNotMatch(html,/data-plano-quick="1.3.1"|data-plano-quick="2.6.3.1"/);});
